### ISSUE TITLE
with-nginx-proxy (with letsencrypt) did not work

### ISSUE THREAD

**Issue by chsachs** [nextcloud/docker#1113] opened 2020-05-08 09:18 UTC
I just shortly want to place my issue, it took me several hours to fix it:
I run docker on alpine in a freenas VM. (ok, it's a bit wired, but this works best for me. freenas nextcloud plugin does not run smoothly, I want to have an instance working here to take advantage of my NAS storage). I found out, that simply the containers take too long to come up and due to interference finally the ssl cert was not issued.
What did not work: "docker-compose up -d"

The solution is fire the conainers up staggered:
docker-compose up -d db
docker-compose up -d app
docker-compose up -d web
docker-compose up -d proxy

and then finally:

docker-compose up -d letsencrypt-companion

Maybe this helps someone.

**Comment by ismailyenigul** [comment] 2020-05-09 22:26
Hi @chris2013 
I created a docker-compose.yml with Traefik 2.0 it is much easier than letsencrypt-companion and nginx deployment
You can get it from https://gist.github.com/ismailyenigul/f03b4f5f15e5e61ac5b80905c5d2890a

**Comment by chris2013** [comment] 2020-05-10 09:12
Thank you ismail, I will investige once I find some time. Traefik really seems to be a good solution.
I need to do some research how to setup all the docker stuff, networks e.g. .
best regards,
Christian

**Comment by Motophan** [comment] 2020-05-10 12:54
@chris2013 do not use this, his image wont pass the trusted ssl cert.

**Comment by chris2013** [comment] 2020-05-13 09:40
I finally decided to run the insecure solution within my network. Next step is to setup a proxy on opnsense who handles the letsencrypt stuff. A useful guideline (in German) is this one: https://www.triumvirat.org/2020/02/17/haproxy-reverse-proxy-mit-lets-encrypt-zertifikaten-unter-opnsense-20-1/

**Comment by candyacao** [comment] 2020-05-22 23:18
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml

**Comment by AkgunFatih** [comment] 2020-07-02 02:15
@ismailyenigul Cok tessekur ederim abim

**Comment by joshtrichards** [comment] 2023-10-21 02:08
Hi @chsachs - Thanks for your contribution! I encourage you to post these sorts of things at the Nextcloud Help Forum: https://help.nextcloud.com

(There is a wiki and how to section there too).

I'm going to close this issue out since it's been 3+ years and it's not a bug in the Docker image. It'll still be searchable if someone searches the Issues, but will no longer appear as "open" since there isn't anything actionable here to be done. Thanks again!

**Closed by joshtrichards** 2023-10-21 02:08 UTC
