### ISSUE TITLE
 ImagickException: Failed to read the file at <<closure>>

### ISSUE THREAD

**Issue by despens** [nextcloud/docker#741] opened 2019-05-05 19:40 UTC
Using the [Apache "full" Dockerfile](https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/apache/Dockerfile) with nextcloud 15.0.7, ImageMagick is unable to generate previews for PDF files. Is there a component missing in the image?

<details>
<summary>nextcloud error log</summary>

[core] Error: ImagickException: Failed to read the file at <<closure>>

 0. /var/www/html/lib/private/Preview/Bitmap.php line 87
    readimage("/tmp/oc_tmp_tb7JuP-.pdf[0]")
 1. /var/www/html/lib/private/Preview/Bitmap.php line 50
    getResizedPreview("/tmp/oc_tmp_tb7JuP-.pdf", 4096, 4096)
 2. /var/www/html/lib/private/Preview/GeneratorHelper.php line 59
    getThumbnail("RHIZOME EXEMPT 501(c)(3).pdf", 4096, 4096, false, OC\Files\View {})
 3. /var/www/html/lib/private/Preview/Generator.php line 194
    getThumbnail(OC\Preview\PDF {}, OC\Files\Node\File {}, 4096, 4096)
 4. /var/www/html/lib/private/Preview/Generator.php line 118
    getMaxPreview(OC\Files\SimpleFS\SimpleFolder {}, OC\Files\Node\File {}, "application/pdf")
 5. /var/www/html/lib/private/PreviewManager.php line 205
    getPreview(OC\Files\Node\File {}, 250, 250, true, "fill", "application/pdf")
 6. /var/www/html/core/Controller/PreviewController.php line 175
    getPreview(OC\Files\Node\File {}, 250, 250, true, "fill")
 7. /var/www/html/core/Controller/PreviewController.php line 147
    fetchPreview(OC\Files\Node\File {}, 250, 250, false, false, "fill")
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
    getPreviewByFileId(2298, 250, 250, false, false, "fill")
 9. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OC\Core\Controller\PreviewController {}, "getPreviewByFileId")
10. /var/www/html/lib/private/AppFramework/App.php line 118
    dispatch(OC\Core\Controller\PreviewController {}, "getPreviewByFileId")
11. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", OC\AppFramework\ ... {}, {_route: "core.P ... "})
12. <<closure>>
    __invoke({_route: "core.P ... "})
13. /var/www/html/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "core.P ... "})
14. /var/www/html/lib/base.php line 987
    match("/core/preview")
15. /var/www/html/index.php line 42
    handleRequest()

GET /core/preview?fileId=2298&c=5cbabfa75c94e&x=250&y=250&forceIcon=0
from 87.180.237.6 by admin at 2019-05-05T15:25:51+00:00

</details>

**Comment by J0WI** [comment] 2021-02-19 15:22
Duplicate of #981

**Closed by J0WI** 2021-02-19 15:22 UTC
