### ISSUE TITLE
/upgrade.exclude should not exclude special config files like reverse-proxy.config.php

### ISSUE THREAD

**Issue by flortsch** [nextcloud/docker#1837] opened 2022-10-14 18:03 UTC
Currently, the entrypoint of the Docker image rsyncs original source files from `/usr/src/nextcloud/` to `/var/www/html/` if it detects that a newer version is running. The rsync command excludes paths from being overwritten by using the file `/upgrade.exclude`. The content of this file is currently:

```
/config/
/data/
/custom_apps/
/themes/
/version.php
/nextcloud-init-sync.lock
```

This is problematic, because it excludes all php files in `/config/`, i.e., also special config files such as `reverse-proxy.config.php` used by the Docker image itself to support special environment variables.

In my specific case, this resulted in the container not picking up the newly introduced environment variable `OVERWRITECLIURL` that I wanted to use, as my old reverse-proxy.config.php file was excluded from the sync.

My suggestion would be to only exclude `/config/config.php`, or maybe better, exclude `/config/` but specifically include all the special config files used by this image, such as `reverse-proxy.config.php`, `smtp.config.php`, and so on.

**Comment by joshtrichards** [comment] 2023-10-23 16:15
Duplicate of #1533 

Let's consolidate tracking for this matter there. (PS: I like your last proposed approach!)

**Closed by joshtrichards** 2023-10-23 16:15 UTC
Labels: bug
