### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by STR3IKERKRYPTON** [nextcloud/docker#1921] opened 2023-02-14 06:25 UTC
I am currently using Nextcloud and PostgreSQL in a Docker container. I used "latest" as the image tag for both. Yesterday everything worked without any problems, but since today I get the following error message when calling up the Nextcloud web interface:

Internal server error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

I haven't changed any config since yesterday.
I had this problem before and just reinstalled the Nextcloud and PostgreSQL container.

[Nextcloud Server Log](https://pastebin.com/tuuH59dS)
[PostgreSQL Log](https://pastebin.com/EEGb8emu)

Does anyone also got this problem?
Thanks in advance.

**Comment by STR3IKERKRYPTON** [comment] 2023-02-14 07:51
I found out that the PostgreSQL Container IP has changed. I then recreated the Nextcloud container and adjusted the POSTGRES_HOST env variable. Still get the same error.

**Comment by Wubarius** [comment] 2023-02-15 11:59
Hi,

After updating to 25.0.3, my nextcloud environment no longer starts.

Unfortunately that doesn't help - add ServerName in Apache2 config
/etc/apache2/apache2.conf
ServerName "name"

apache2ctl configtest
Syntax ok
URL same error

Container Log:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message

URL:
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

**Comment by STR3IKERKRYPTON** [comment] 2023-02-17 09:32
I found this thread on github: https://github.com/nextcloud/docker/issues/609
I've added NEXTCLOUD_HOSTNAME to my docker env variables but nothing changed.

**Comment by joshtrichards** [comment] 2023-07-21 20:18
Hi @STR3IKERKRYPTON & @Wubarius - You both need to check your `nextcloud.log` for clues about the cause of the internal server errors.

And, @Wubarius, the Apache ServerName is unlikely to be the cause of your internal server errors. That's generally a relatively innocuous warning. The internal server errors, however, are another matter.

Also, @STR3IKERKRYPTON, I'm unclear why IP addressing is coming up. Are you not letting Docker connect your containers with their names? Are you using a Compose file? If so, post it. Also, I would not tag to latest unless you are extremely careful - you could end up upgrading unintentionally (and possibly in several challenging to reverse ways).

**Comment by joshtrichards** [comment] 2023-10-29 01:04
Unfortunately the logs from the Apache level are not going to be sufficient. To diagnose the cause of the 500 error you will need to look at your `nextcloud.log` located in your data directory. The easiest way to view that is probably to open an interactive shell in your Nextcloud app container.

**Comment by joshtrichards** [comment] 2023-10-29 01:07
Closing, due to insufficient information to troubleshoot nor suggest this is a bug. Hopefully you got this figured out through other channels.

Chances are this is a configuration matter, but feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com) if you encounter similar problems again.

**Closed by joshtrichards** 2023-10-29 01:07 UTC
Labels: question, needs info
