### ISSUE TITLE
Bad syntax for user creation in PostgreSQL

### ISSUE THREAD

**Issue by talavis** [nextcloud/docker#1083] opened 2020-04-21 06:22 UTC
I'm trying to use the `nextcloud:18` container with a PostgreSQL database (`postgres:11`). Upon start, the log of the container is:
```
Initializing nextcloud 18.0.3.0 ...
Initializing finished
New nextcloud instance
Installing with PostgreSQL database
starting nextcloud installation
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "oc_nextcloud-admin"
 -> 
retrying install...
```
When checking the log for the database, I noticed:
```
<date> [237] ERROR:  syntax error at or near "-" at character 25
<date> [237] STATEMENT:  CREATE USER oc_nextcloud-admin CREATEDB PASSWORD 'xzmp9smq2sv24yuh0mwmrkxe7eh4p4'
<date> [238] FATAL:  password authentication failed for user "oc_nextcloud-admin"
<date> UTC [238] DETAIL:  Role "oc_nextcloud-admin" does not exist.
```
So it seems that the syntax that is used to create the user is incorrect. In PostgreSQL 11, the syntax for creating a user with `-` in the name must use `"`, so the above should be:
```
CREATE USER "oc_nextcloud-admin" CREATEDB PASSWORD 'xzmp9smq2sv24yuh0mwmrkxe7eh4p4'
```
For now I'm stuck being unable to use it.

**Comment by talavis** [comment] 2020-04-21 12:57
The problem in this case is the aforementioned `-` in the username. Would still be great to at least have a warning about it, or e.g. the above fix to make it work.

**Comment by kesselb** [comment] 2020-04-23 06:59
Closing as duplicate of https://github.com/nextcloud/server/issues/13318

**Closed by kesselb** 2020-04-23 06:59 UTC
