### ISSUE TITLE
Update / directory permission for rootless mode (apache image)

### ISSUE THREAD

**Issue by jaeha-choi** [nextcloud/docker#1762] opened 2022-06-02 07:20 UTC
Current `/` permission (`500`, owned by `root`) prevents non-root users (`www-data`) from searching through `/var/www/html` directory:
```
...
(13)Permission denied: ... access to / denied (filesystem path '/var') because search permissions are missing on a component of the path
...
```
If I enter the docker container and update the permission to 501, it works just fine. But it seems like 555 is reasonable since fpm image is using 555 for `/`.

The permission itself is more of an upstream issue, but I'm submitting this issue anyway since nextcloud image already updates permissions for a few directories.

**Comment by joshtrichards** [comment] 2024-06-18 19:42
I can't reproduce this behavior. Can you provide a Compose (or run command) that should reproduce this behavior?

And I don't see anything resembling these permissions anywhere. Are you sure this wasn't something inherited from a bind mount from the underlying host or something?

**Comment by joshtrichards** [comment] 2024-10-08 00:23
Closing due to inability to reproduce and a lack of follow-up info needed to determine a course of action.

**Closed by joshtrichards** 2024-10-08 00:23 UTC
Labels: bug, needs info, rootless
