### ISSUE TITLE
Warning no default phone region set 

### ISSUE THREAD

**Issue by m0rtalis** [nextcloud/docker#1465] opened 2021-04-05 14:03 UTC
With nextcloud 21.0 there is a new warning saying

> Your installation has no default phone region set. This is required to validate phone numbers in the profile settings without a country code. To allow numbers without a country code, please add "default_phone_region" with the respective ISO 3166-1 code of the region to your config file.

It was briefly discussed in issue #1414 this setting should be settable with an environment variable. Currently it seems like I have to edit the config.php just for this one setting.

**Comment by nathanael-h** [comment] 2021-06-24 08:24
Hello, can someone confirm or not if to solve this we need to add this env variable in autoconfig.php files (eg : https://github.com/nextcloud/docker/blob/master/21.0/apache/config/autoconfig.php ) ?

**Comment by tmo1** [comment] 2022-01-12 19:14
It would indeed be nice to allow this to be set via an environmental variable, but it can be set from the command line like this:
```
# docker-compose exec --user www-data <app> php occ config:system:set default_phone_region --value="US"
```
where `<app>` is the name of the nextcloud service in the nextcloud `docker-compose.yml`.

I found this in [this thread](https://github.com/nextcloud/server/issues/24738).

**Comment by joshtrichards** [comment] 2023-07-23 14:40
Also see https://github.com/nextcloud/docker/issues/1544#issuecomment-1370172015

I doubt an additional environment variable just for Docker will be added for this. THE `NC_*` variables are a sufficient workaround for those that need it to be entirely in their Compose file IMO.

For the most part, I think we should nudge Nextcloud Server - rather than the community Docker image - towards more extensive and robust `NC_*` support - e.g. https://github.com/nextcloud/documentation/pull/9143#issuecomment-1238598774

This is mostly an upstream (NC Server) matter. This issue should probably get closed out here.

**Comment by tigerblue77** [comment] 2023-07-23 15:29
@joshtrichards I think TZ environment variable is a good practice when it comes to docker containers

**Comment by joshtrichards** [comment] 2023-11-04 16:57
Even though a later issue was closed as a duplicate of this one, the discussion was more extensive there after it was closed. If you want to see this, use the NC_* variable noted: https://github.com/nextcloud/docker/issues/1544#issuecomment-1370172015

**Closed by joshtrichards** 2023-11-04 16:57 UTC
Labels: enhancement, feature: auto config (environment variables)
