### ISSUE TITLE
php.ini probably not correctly set

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/docker#1626] opened 2021-11-05 20:34 UTC
Hello,

When running `php --ini`I noticed that `/usr/local/etc/php/php.ini-production` is not read. Maybe this file should be copied to `/usr/local/etc/php/php.ini`. But I'm not entirely sure.

**Comment by J0WI** [comment] 2022-02-02 23:22
Duplicate of https://github.com/docker-library/php/issues/873

**Closed by J0WI** 2022-02-02 23:22 UTC
