### ISSUE TITLE
Dockercompose examples for Let's Encrypt probably need updating

### ISSUE THREAD

**Issue by PathToLife** [nextcloud/docker#1362] opened 2021-01-08 16:56 UTC
What:
`jrcs/letsencrypt-nginx-proxy-companion:latest`
Has changed, it now needs a new persistent volume
`./letsencrypt-acme:/etc/acme.sh # NEW CHANGE`

https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/730#issuecomment-748936276

> The single most important change is that the container now requires a volume mounted to /etc/acme.sh in order to persist ACME account keys and SSL certificates. The last tagged version that uses simp_le is v1.13.1.

Effects of not applying this new change:
- letsencrypt-nginx-proxy-companion will recreate new certificates and accounts on each `docker-compose down` -> `... up` cycle
- this will case a rate limit error, after 5 restarts (within a week); next-cloud will not be accessible on the 6th restart (self signed cert error)
- also lets encrypt account creation rate limit will kick in while you try to figure out what's going on 🤦‍♂️😂

My config using bind mounts with new volume applied:
`./letsencrypt-acme:/etc/acme.sh # NEW CHANGE`

```  
letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
            - ./letsencrypt-acme:/etc/acme.sh # NEW CHANGE
            - ./letsencrypt-certs:/etc/nginx/certs:rw
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - proxy-tier
        depends_on:
            - proxy
```

After i'm no longer rate limited and can confirm my config, I'll make a PR to https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml

Not confident with other docker-compose files (I'm new to them) but perhaps @SnowMB or @tilosp? :)

**Comment by PathToLife** [comment] 2021-01-09 03:08
https://github.com/nextcloud/docker/pull/1358

**Comment by crenz** [comment] 2021-02-10 10:14
Thank you for researching this, I ran into the exact same issue.

**Comment by mblo** [comment] 2021-02-25 15:33
Looks like a duplicate of  #1357

**Comment by snkaupe** [comment] 2021-04-06 15:46
I've been hit by this today when updating my private Nextcloud installation. I added the fix proposed by @PathToLife , but my Nextcloud is still unreachable due to only serving a self-signed certificate instead of one by Let's Encrypt. Could it be that the config files for nginx need an update, too? My log file always lists the following error message since the update:

```
Apr 06 17:14:48 <server-name> start.sh[16415]: letsencrypt-companion_1  | [Tue Apr  6 15:14:48 UTC 2021] <subdomain.domain.tld>:Verify error:Invalid response from http://<subdomain.domain.tld>/.well-known/acme-challenge/XYLgXuxmCwVGPwNqsdxJxEQXZbLT1G_PRqOyXG2vyEE [185.163.116.224]:
Apr 06 17:14:48 <server-name> start.sh[16415]: letsencrypt-companion_1  | [Tue Apr  6 15:14:48 UTC 2021] Please check log file for more details: /dev/null
```

**Comment by niemsoen** [comment] 2023-09-02 06:06
> I've been hit by this today when updating my private Nextcloud installation. I added the fix proposed by @PathToLife , but my Nextcloud is still unreachable due to only serving a self-signed certificate instead of one by Let's Encrypt. Could it be that the config files for nginx need an update, too? My log file always lists the following error message since the update:
> 
> ```
> Apr 06 17:14:48 <server-name> start.sh[16415]: letsencrypt-companion_1  | [Tue Apr  6 15:14:48 UTC 2021] <subdomain.domain.tld>:Verify error:Invalid response from http://<subdomain.domain.tld>/.well-known/acme-challenge/XYLgXuxmCwVGPwNqsdxJxEQXZbLT1G_PRqOyXG2vyEE [185.163.116.224]:
> Apr 06 17:14:48 <server-name> start.sh[16415]: letsencrypt-companion_1  | [Tue Apr  6 15:14:48 UTC 2021] Please check log file for more details: /dev/null
> ```

 @snkaupe Hey Sebastian, how did you solve it / did you solve it? I have the same issue! Thanks for the reply :)

**Closed** 2023-09-03 14:04 UTC
