### ISSUE TITLE
php-imagick do not support SVG

### ISSUE THREAD

**Issue by OrvilleQ** [nextcloud/docker#1583] opened 2021-09-13 09:42 UTC
Image: 22.1.1

After fresh installation, I got this warning:

![image](https://user-images.githubusercontent.com/21377465/133061782-4d4d235c-fbcc-4ced-9403-717bfd857272.png)

It says php-imagick do not support SVG, please install for better compatibility.

After install `libmagickcore-6.q16-6-extra` with `apt`, I solve this problem. Please consider add this package to the Dockerfile.

**Comment by jsalatiel** [comment] 2021-09-13 12:28
Also got this message after upgrade from 20 to 21.

![image](https://user-images.githubusercontent.com/5522389/133083405-0a59f1da-9b3c-4554-8c28-1c01325263fe.png)

**Comment by BorussiaPlayer17** [comment] 2021-09-19 11:15
https://github.com/nextcloud/docker/issues/1414

**Comment by J0WI** [comment] 2021-09-20 21:28
Duplicate of #1414

**Closed by J0WI** 2021-09-20 21:28 UTC
