### ISSUE TITLE
Resetting password does not work

### ISSUE THREAD

**Issue by MartiniMoe** [nextcloud/docker#713] opened 2019-04-10 11:59 UTC
Hi there,

I have the following issue:

When I create a new user, or an existing user clicks on "Forgot password?" he/she gets an email with a link to set a new password.

But when he/she clicks the link, opens the form, enters the new password an clicks on "Reset password" nothing happens at all.

I tried this on firefox and chromium and on 3 different machines. Any ideas?

Thanks! :)

**Comment by J0WI** [comment] 2019-06-14 13:08
Is this because of the Docker container or is this an issue in NextCloud itself?
What means "nothing happens"? Is there an url and does it open?
Do you use the encryption module or a proxy?

**Comment by konwin** [comment] 2019-07-09 09:12
I have the same problem. The site for password reset loads and I can enter a password but after entering a passord and pressing the button nothing happens.
Firefox tells me the password field is "insecure", but the connection details show my certificate and that the site is secure!
My nextcloud installation is a docker one running behind a traefik proxy with a wildcard certificate.
Here is my docker-compose.yml
[docker-compose.yml.txt](https://github.com/nextcloud/docker/files/3372170/docker-compose.yml.txt)
Any ideas how to track whats geoing wrong?

**Comment by diederikdegraaf** [comment] 2019-10-03 10:50
The form for resetting the password uses http. When I edit the URL to https (e.g. in the devtools console), it works.

https://github.com/nextcloud/server/issues/13700

**Comment by J0WI** [comment] 2019-10-03 12:10
Duplicate of #742

**Closed by J0WI** 2019-10-03 12:10 UTC
