### ISSUE TITLE
Do I Need to Address the AH00558 Warning in Nextcloud Docker with Apache's ServerName Directive?

### ISSUE THREAD

**Issue by jreimone** [nextcloud/docker#2055] opened 2023-08-12 08:37 UTC
I run the image in version `nextcloud:27.0.2-apache` behind a dockered reverse proxy (don't know if it's relevant). When I attach to the logs via `docker-compose logs -f nextcloud` I see the following line when the container starts.

```bash
nextcloud         | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using <MY_CONTAINER_IP>. Set the 'ServerName' directive globally to suppress this message
```

My instance is fully working and also accessible via my domain but I'm wondering if I can help Apache here? Do I need to worry?

**Comment by joshtrichards** [comment] 2023-08-13 13:57
No. It doesn't impact operations. It's merely the result of a Debian default for Apache when it runs in Docker. You can set your `ServerName` to `localhost` if you wish to get rid of the message.

Duplicate of https://github.com/docker-library/php/pull/647

Side note: We should probably add this, along with some others, to the repository README and/or a FAQ.

**Comment by jreimone** [comment] 2023-08-16 06:08
Thanks for the explanation @joshtrichards 🙏 Out of curiosity, how would I set the `ServerName` for the running container?

**Comment by joshtrichards** [comment] 2023-08-26 14:34
There are multiple ways one could do it.

The directive is in `/etc/apache2/apache2.conf`.

For the change to persist either mounting over that file or adding the change to a custom local Dockerfile sort of like in this previously proposed patch:

https://github.com/nextcloud/docker/pull/1855

**But beware these could break future updates since you'll no longer be using the image provided apache2.conf or Dockerfile. So unless you already have reason to make local customizations via one of these methods it's probably more work/risk than is worth it**

Personally I just ignore it and hope it eventually gets fixed upstream (preferred) in the `php` base image.

**Closed** 2023-08-26 14:36 UTC
Labels: question, docs

**Comment by meonkeys** [comment] 2023-08-26 16:22
FWIW, I only see `ServerName` in `/etc/apache2/sites-available/000-default.conf` in my running `nextcloud:27.0.2-apache` container, and it is commented out.

I also feel that itch to fix it (and barely stop myself every time, realizing it really ain't broke and it's OK to ignore the warning).

That said... if I *were* to scratch that itch and fix it, I would make a small conf file somewhere on the host, say `/opt/nextcloud-apache/servername.conf`. In there, I'd put something like:

```
ServerName nextcloud.example.com
```

And in my `docker-compose.yml` I'd provide that to the container with:

```
    volumes:
      - /opt/nextcloud-apache/servername.conf:/etc/apache2/conf-enabled/servername.conf
```

That would probably work, if I'm reading <https://httpd.apache.org/docs/2.4/mod/core.html#servername> correctly.
