### ISSUE TITLE
imagemagick does not work properly

### ISSUE THREAD

**Issue by mayswind** [nextcloud/docker#1355] opened 2021-01-06 04:23 UTC
Hi,
I use the official `nextcloud:20.0.4-fpm-alpine` image, and I find the HEIC file cannot generate preview correctly (show "Error loading xxxx.heic", and "nc:has-preview" in response is false), then I use this command to check imagemagick.

```
$ php --ri imagick

imagick

imagick module => enabled
imagick module version => 3.4.4
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 7.0.10-48 Q16 x86_64 2020-12-12 https://imagemagick.org
Imagick using ImageMagick library version => ImageMagick 7.0.10-48 Q16 x86_64 2020-12-12 https://imagemagick.org
ImageMagick copyright => © 1999-2020 ImageMagick Studio LLC
ImageMagick release date => 2020-12-12
ImageMagick number of supported formats:  => 0

Directive => Local Value => Master Value
imagick.locale_fix => 0 => 0
imagick.skip_version_check => 0 => 0
imagick.progress_monitor => 0 => 0
```

The above info shows there are no supported format for imagemagick. Then I find this issue (https://gitlab.alpinelinux.org/alpine/aports/-/issues/11522), and as Andy Postnikov says "I found that `apk add imagemagick` required to make list available formats It means that `imagemagick-libs` is not enough to work properly". So I run `apk add imagemagick`, and this problem has been solved.

Does the official image add this package?

**Comment by J0WI** [comment] 2021-01-07 19:07
Duplicate of https://github.com/nextcloud/docker/issues/759

**Closed by J0WI** 2021-01-07 19:07 UTC
