### ISSUE TITLE
Apache2 Remoteip does not seem to work for local ip's

### ISSUE THREAD

**Issue by beertje44** [nextcloud/docker#1893] opened 2023-01-07 03:02 UTC
Stubled upon this in my own quest to get ip’s working in apache2. In the end it wasn’t all that hard:

Just don’t set APACHE_DISABLE_REWRITE_IP env var, its value doesn’t seem to matter. If it’s there remoteip in apache2 gets disabled by nextcloud. Without this it kind of just works for reverse proxies that provide the X-Real-Ip and are in the private ip range. Which is pretty much what you would expect in a docker based setup.
BUT: RemoteIPTrustedProxy does not work for internal ip’s, guess some people are ok with this and you’re done now. But there is also RemoteIPInternalProxy, because I use podman with a systemd config file all I needed to do was add:
ExecStartPost=/usr/bin/podman exec -it nextcloud_app /bin/bash -c ‘sleep 5 && rm -f /etc/apache2/conf-available/remoteip.conf && echo -e “RemoteIPHeader X-Real-IP\nRemoteIPInternalProxy 10.0.0.0/8” > /etc/apache2/conf-available/remoteip.conf && /usr/sbin/service apache2 reload’

To my nextcloud-app systemd Unit file.

I do realise this is not stricly the way to go on a docker container, but don’t see how this would change. Nevertheless, perhaps somebody @nextcloud could consider this?

PS I recall reading somewhere APACHE_DISABLE_REWRITE_IP was a security measure when using a reverse proxy. If this is the case I wonder how one is supposed to get proper logging? apache2 logs traffic, and nextcloud.log is for errors IIRC.

**Comment by meonkeys** [comment] 2023-01-11 18:05
Thanks for writing this up as well as https://help.nextcloud.com/t/how-to-get-the-real-ips-in-logs/83096/36 !

Could you write a patch / pull request for this? I'd also like to see real local IPs. Maybe use wwe's suggestion to mount an extra config file.

**Comment by beertje44** [comment] 2023-03-08 13:41
Agree, this is more elegant and works just fine too :) However this is added personal config, I really think this should be fixed upstream. If I'm not mistaken there are env_vars for trusted proxies and the remoteip.conf file is therefor not static, but I could be wrong. Will have a look at it.

**Comment by joshtrichards** [comment] 2023-11-04 16:30
Duplicate of #1103 and fixed by #2004.

**Closed by joshtrichards** 2023-11-04 16:30 UTC
Labels: enhancement, question, feature: auto config (environment variables), integration: proxy
