### ISSUE TITLE
store only the config and data folder

### ISSUE THREAD

**Issue by Andrysky** [nextcloud/docker#822] opened 2019-07-27 18:55 UTC
I store /var/www/html in a network folder on another computer, because of this nextcloud work slowly( .
Is it possible to store only configs and date? (so that the nextcloud was "stateless")

**Comment by J0WI** [comment] 2020-06-05 15:41
Please have a look at the example: https://github.com/nextcloud/docker#persistent-data

**Comment by Andrysky** [comment] 2020-06-06 07:26
volumes:
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes/

without 
      - html:/var/www/html

i recive 


      retrying install...
      Command maintenance:install is not defined.  
      Did you mean one of these?          
      app:install    
      maintenance:data-fingerprint
      maintenance:mimetype:update-db          
      maintenance:mimetype:update-js     
      maintenance:mode               
      maintenance:repair 
      maintenance:theme:update                 
      maintenance:update:htaccess                
      installing of nextcloud failed!

I should not store /var/www/html this is part of the container

if nextcloud needs to save something outside the database, this must be done in one of these folders
/var/www/html/config local configuration
/var/www/html/data the actual data of your Nextcloud

**Comment by 3-w-c** [comment] 2020-09-27 23:59
It looks like [`docker-entrypoint.sh` is looking for `/var/www/html/version.php`](https://github.com/nextcloud/docker/blob/f1b22e0ceebfec9cc03454809cf36ceb641b82b9/19.0/apache/entrypoint.sh#L75):

```
if [ -f /var/www/html/version.php ]; then
    # shellcheck disable=SC2016
    installed_version="$(php -r 'require "/var/www/html/version.php"; echo implode(".", $OC_Version);')"
fi
```

A quick-fix might be to copy this file into `config` after running `occ maintenance:install` and symlink it there (for compatibility with anything else which is looking for it in that location) if it's found on start-up before doing the above version check.

**Comment by 3-w-c** [comment] 2020-09-28 00:03
Actually this is already in progress in !588, and this issue is possibly a duplicate of #489 :flushed:

**Comment by joshtrichards** [comment] 2023-10-21 01:29
> I should not store /var/www/html this is part of the container

Really it's not. The container has an associated version of the Nextcloud installer located in `/use/src/nextcloud` within the image. That's part of the container (image really). The *installer* for NC runs from there, but it's not useful for anything else. It installs into /var/www/html. Installation entails changes and there are bits within /var/www/html that are, in fact, stateful (and thus necessary to keep around). That's why the persistent data requirement is defined as "anything under /var/www/html" in the docs (README).

Some people choose to split up bits of the persistent data onto different volumes rather than one single one, but the persistent data covered doesn't change.

Don't get me wrong - yes there are different ways this might be done that would structure things a bit differently, but...

> If nextcloud needs to save something outside the database, this must be done in one of these folders
/var/www/html/config local configuration
/var/www/html/data the actual data of your Nextcloud

Then you need to take that up with [Nextcloud Server](https://github.com/nextcloud/server) not the community Docker image here. :-)

> I store /var/www/html in a network folder on another computer, because of this nextcloud work slowly( .
Is it possible to store only configs and date? (so that the nextcloud was "stateless")

Just consider all of `/var/www/html` your data.  Or see above... because changing that is out of scope for the Docker image to address. It's a byproduct of the Nextcloud Server's installation/update architecture.

I'm going to close this issue since it hasn't seen any activity for more than 3 years. It seems addressed and/or out-of-scope for the Docker image itself. I do hope you found a deployment model that worked for you on the mean time. Thanks for contributing to Nextcloud!

**Closed by joshtrichards** 2023-10-21 01:29 UTC
Labels: question
