### ISSUE TITLE
Apache process shutting down on SIGWINCH

### ISSUE THREAD

**Issue by merlinscholz** [nextcloud/docker#1423] opened 2021-02-24 17:11 UTC
Hi, when using the docker:stable container (and all other non-fpm labels), viewing the Docker logs on some systems (for example on Synology DiskStations) causes a SIGWINCH to be send to the Apache2 process. This causes it to shutdown gracefully. If auto-restarting is enabled, this process repeats as long as the according log window is left open.

A workaround is to only use docker command over ssh on those systems.

**Comment by J0WI** [comment] 2021-03-14 18:15
I suspect this is an issue with Docker on Synology and not caused by the Nextcloud image.

**Comment by merlinscholz** [comment] 2021-03-27 21:12
I was mainly wondering if terminating on SIGWINCH is a function that should be enabled in the Nextcloud image, since I do not see any reason in which a SIGWINCH should cause Nextcloud to stop. Apache2 mainly implemented this feature to allow graceful shutdowns (https://bz.apache.org/bugzilla/show_bug.cgi?id=50669). Other projects have the same issue and worked around it: https://github.com/GrahamDumpleton/mod_wsgi/issues/105#issuecomment-359783948

**Comment by James-Quigley** [comment] 2021-05-22 20:46
`[mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully`

Also getting a `SIGWINCH` error running the apache container

**Comment by James-Quigley** [comment] 2021-05-23 19:20
Also appears to be an issue when running within kubernetes if the system is using [containerd](https://github.com/containerd/containerd/blob/261c107ffc4ff681bc73988f64e3f60c32233b37/cmd/ctr/commands/tasks/tasks_unix.go#L54). And apache uses SIGWINCH as a graceful termination signal (https://httpd.apache.org/docs/2.4/en/stopping.html#gracefulstop)

**Comment by J0WI** [comment] 2021-05-25 08:44
See also https://github.com/docker-library/php/issues/877 and https://github.com/docker-library/php/issues/907

**Comment by AndrewwHummer** [comment] 2022-04-28 07:56
Do we have a workaround for this? We see this behaviour with k8s and containerd too. This is kinda a show stopper :(

**Comment by SNThrailkill** [comment] 2022-05-20 14:59
Also having this issue with K8s and using the helm chart

**Comment by grglzrv** [comment] 2022-07-04 20:37
the same here, you need to use nextcloud:fpm (with fpm tag) + nginx enabled

**Comment by Robproject** [comment] 2022-07-25 23:27
same error with bare metal installation and opening nextcloud talk app

**Comment by golgotow** [comment] 2022-12-30 05:53
still no fix ?

**Comment by umarmughal824** [comment] 2023-04-20 07:57
I am also facing that issue.

**Comment by QuinnBast** [comment] 2023-07-17 17:18
Just wanted to comment here. I was running into this problem as well. I fixed this problem after properly setting my `config.php` files. When using the default docker image, the default configurations that come with don't quite work I guess, so I had to (with docker: use `-v` to volume mount additional configuration files into the right spot), or, with the kubernetes helm chart, I had to set the proper config settings in either `nextcloud.configs` or `nextcloud.defaultConfigs`, or `nextcloud.phpConfigs`. Once I had the right configuration files in place it started working.

**Comment by MannerMan** [comment] 2023-07-26 07:33
I was able to work-around this with nextcloud on k3s without rebuilding the offical docker image by mounting a trap wrapper script that traps the SIGWINCH signal, thereby not passing it to apache.

nextcloud deployment.yml:
```
[...]
          spec:
            volumes:
            - name: nextcloud-trap
              configMap:
                name: nextcloud-trap
                defaultMode: 0777 # < to ensure script can be executed
            containers:
            - image: nextcloud:26
              name: nextcloud
              command: ["/bin/bash", "-c"]
              args:
              - /nextcloud_trap.sh
[...]
              volumeMounts: 
              - name: nextcloud-trap
                mountPath: /nextcloud_trap.sh
                subPath: nextcloud_trap.sh
```

nextcloud trap configmap:
```
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nextcloud-trap
        namespace: default
      data:
        nextcloud_trap.sh: |
          trap "" SIGWINCH
          /entrypoint.sh apache2-foreground
```

**Comment by kolAflash** [comment] 2024-02-02 17:01
Workaround to prevent SIGWINCH from reaching the Apache process:  
`setsid COMMAND`  
Replace "COMMAND" with the actual command.

&nbsp;

Workaround keeping the process in foreground and forwarding SIGINT (ctrl-c):
```
setsid --wait COMMAND &
child_pid=$!
trap "kill -SIGINT $child_pid" SIGINT
wait $child_pid
```

&nbsp;

For "setsig" see also: https://en.wikipedia.org/wiki/Process_group

**Comment by j-bolivar-lt** [comment] 2024-03-28 10:51
Definitely there's an issue with the image/helm configuration.

This one worked for me:

```
flavor: apache
version: 4.5.12
```

**Comment by joshtrichards** [comment] 2024-10-09 16:33
This issue has several different pathways to SIGWINCH/WINCH related matters. Not everyone's situation is the same so the solutions are going to be a bit different.

Start-up errors:

- https://github.com/nextcloud/helm/issues/377#issuecomment-2254352255
- #2054 
- If using Helm, see https://github.com/nextcloud/helm/tree/main/charts/nextcloud#logging

When opening a shell into a container:

- The exact command you use to do this matters a great deal since there it's tied to the tty
- OP's matter could likely be addressed by changing the command they're using to exec into the container

I'm going to close this since there are different matters ending up here. And there isn't a clear bug in the image itself.

If you believe strongly you're experiencing a bug in the image itself, please create a dedicated Issue with precise reproduction steps.

**Closed by joshtrichards** 2024-10-09 16:33 UTC
Labels: upstream, k8s/helm/etc
