### ISSUE TITLE
500 Internal Server Error: signal 29 (SIGIO) received

### ISSUE THREAD

**Issue by gyurmogyuri** [nextcloud/docker#1769] opened 2022-06-12 14:42 UTC
Hello, If i open https page, i got errors:
```
500 Internal Server Error
nginx/1.21.6
```
```
nextcloud-letsencrypt-companion-1  | 2022/06/12 14:18:41 Generated '/app/letsencrypt_service_data' from 7 containers
nextcloud-letsencrypt-companion-1  | 2022/06/12 14:18:41 Running '/app/signal_le_service'
nextcloud-letsencrypt-companion-1  | 2022/06/12 14:18:41 Watching docker events
nextcloud-letsencrypt-companion-1  | 2022/06/12 14:18:42 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nextcloud-letsencrypt-companion-1  | Reloading nginx proxy (ghjkl)...
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 1 (SIGHUP) received from 60, reconfiguring
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: reconfiguring
nextcloud-letsencrypt-companion-1  | 2022/06/12 14:18:43 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nextcloud-letsencrypt-companion-1  | 2022/06/12 14:18:43 [notice] 60#60: signal process started
nextcloud-letsencrypt-companion-1  | Creating/renewal ghjkl.net certificates... (ghjkl.net)
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: using the "epoll" event method
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: start worker processes
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: start worker process 72
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: start worker process 73
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: start worker process 74
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: start worker process 75
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 56#56: gracefully shutting down
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 57#57: gracefully shutting down
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 56#56: exiting
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 57#57: exiting
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 59#59: gracefully shutting down
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 58#58: gracefully shutting down
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 58#58: exiting
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 59#59: exiting
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 57#57: exit
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 56#56: exit
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 58#58: exit
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 59#59: exit
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 17 (SIGCHLD) received from 57
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: worker process 56 exited with code 0
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: worker process 57 exited with code 0
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 29 (SIGIO) received
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 17 (SIGCHLD) received from 56
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 17 (SIGCHLD) received from 59
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: worker process 59 exited with code 0
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 29 (SIGIO) received
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 17 (SIGCHLD) received from 58
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: worker process 58 exited with code 0
nextcloud-proxy-1                  | nginx.1     | 2022/06/12 14:18:43 [notice] 19#19: signal 29 (SIGIO) received
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:44 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:45 UTC 2022] Creating domain key
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:50 UTC 2022] The domain key is here: /etc/acme.sh/g..../g..net/g.....net.key
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:50 UTC 2022] Single domain='g.....net'
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:50 UTC 2022] Getting domain auth token for each domain
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:52 UTC 2022] Getting webroot for domain='g.....net'
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:53 UTC 2022] Verifying: ghjkl.net
nextcloud-letsencrypt-companion-1  | [Sun Jun 12 14:18:56 UTC 2022] Pending
nextcloud-proxy-1                  | nginx.1     | 127.0.0.1 172.19.0.1 - - [12/Jun/2022:14:18:58 +0000] "PROPFIND /remote.php/dav/files/gyurmo/Archiv/Kepek/Bar%C3%A1tok/%C3%81rpi_k%C3%A9pek HTTP/1.1" 503 190 "-" "Mozilla/5.0 (X11; Linux aarch64) KIO/5.94 dolphin/22.04.1" "-"
```
```
version: '3'

services:
  db:
    image: arm64v8/mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mq7M7d6xF5Mffx5
    env_file:
      - db.env

  redis:
    image: arm64v8/redis:alpine
    restart: always

  app:
    image: arm64v8/nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=ghjkl.net
      - LETSENCRYPT_HOST=ghjkl.net
      - LETSENCRYPT_EMAIL=ghjkl@gmai.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: arm64v8/nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 8073:80
      - 8074:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

# self signed
#  omgwtfssl:
#    image: paulczar/omgwtfssl
#    restart: "no"
#    volumes:
#      - certs:/certs
#    environment:
#      - SSL_SUBJECT=servhostname.local
#      - CA_SUBJECT=my@example.com
#      - SSL_KEY=/certs/servhostname.local.key
#      - SSL_CSR=/certs/servhostname.local.csr
#      - SSL_CERT=/certs/servhostname.local.crt
#    networks:
#      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
```

Where do you think have problems.?

**Comment by EpicJosch** [comment] 2022-09-22 18:11
also got the same issue here..

**Comment by feefladder** [comment] 2023-06-12 12:15
See #1608

**Comment by joshtrichards** [comment] 2023-07-22 15:41
Hi @gyurmogyuri - Sorry to hear you ran into difficulty. This appears to be occurring in a container image that has nothing to do with this repository. This channel is used for reporting bugs in the Nextcloud community Docker image (the `app` container in your Compose file), not for general technical support or troubleshooting. You also appear to be building your own images so it's virtually impossible for someone to attempt to reproduce this and help you without additional information about your build. Please take your query to the [Nextcloud Help Forum](https://help.nextcloud.com) or similar.

If you agree with my assessment, please close this Issue out here to avoid confusion. Thanks!

**Comment by joshtrichards** [comment] 2023-11-06 14:56
Please also check your `nextcloud.log` for indications of the root cause. If there is a problem with Nextcloud, there should be clues there, but this problem appears to be in your proxy container which is outside of the scope of this repository. 

I'm going to close this, but feel free to follow-up or open a new issue if there is evidence of an issue with the nextcloud image.

**Closed by joshtrichards** 2023-11-06 14:56 UTC
