### ISSUE TITLE
Error creating New nextcloud instance

### ISSUE THREAD

**Issue by epma01** [nextcloud/docker#731] opened 2019-04-30 08:48 UTC
Caused by Compatibility with docker secrets (Fix #560) #729 
```
+ echo 'New nextcloud instance'
New nextcloud instance
+ file_env NEXTCLOUD_ADMIN_PASSWORD
+ local 'var=NEXTCLOUD_ADMIN_PASSWORD'
+ local 'fileVar=NEXTCLOUD_ADMIN_PASSWORD_FILE'
+ local 'def='
./entrypoint.sh: line 171: syntax error: bad substitution
```

Introduced code is using bash indirect expansion but entrypoint.sh is not using bash and it is not supported
```
file_env() {
    local var="$1"
    local fileVar="${var}_FILE"
    local def="${2:-}"
>>>    if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then    <<< this line is causing the issue
        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
        exit 1
    fi
```

**Comment by tilosp** [comment] 2019-04-30 10:35
cc @J0WI

**Comment by OhioVR** [comment] 2019-04-30 12:55
When I try to instantiate the Nextcloud docker image from docker-compose I get an error "entrypoint.sh: 30: /entrypoint.sh: Bad substitution"

After that point it seems to failing to apply my environment variables. Looks like it should be fixed now however I was wondering if it were posted to docker hub at this time as I haven't seen the change work yet from my docker-compose pull.

**Comment by dassbj01** [comment] 2019-04-30 13:04
Hi,
I experience the same issue ...
on top the linked git tree on docker hub is for sure NOT the one currently published ...
as the "changes" in the entrypoint.sh are NOT reflected.
That is a real blocker. as we are trying to get a zero touch nextcloud installation with configs and apps and therefor we heavily rely on a "stable" release of your image

**Comment by AEPKILL** [comment] 2019-04-30 14:51
i have same issue, please update docker up image.

**Comment by tilosp** [comment] 2019-04-30 15:48
this is expected, the new image will be published to docker hub once https://github.com/docker-library/official-images/pull/5834 is merged

**Comment by J0WI** [comment] 2019-04-30 15:51
An update [is scheduled](https://github.com/docker-library/official-images/pull/5834), I'll investigate to fix the docker secrets feature.

**Comment by conanedogawa2** [comment] 2019-04-30 17:02
Same probleme here.
Reproduce steps are as easy as :
    docker pull nextcloud:latest
    docker run -d -ti --name test nextcloud:latest
    docker logs test

Thanks all for your work here.

**Comment by J0WI** [comment] 2019-04-30 23:59
Containers are now rebuilt and I just added some [tests](https://github.com/docker-library/official-images/pull/5839) to ensure that we catch such regressions before they are committed. Apologize for the inconvenience.

**Closed by J0WI** 2019-04-30 23:59 UTC
