### ISSUE TITLE
fpm-alpine fails with `Command "maintenance:install" is not defined.` after upgrade

### ISSUE THREAD

**Issue by TLATER** [nextcloud/docker#489] opened 2018-10-06 21:19 UTC
Hi, I just upgraded from 13.0 to 14.0.1 with the fpm-alpine image. When starting with the new image I end up with the following repeating message in my logs:

```
<snip>
retrying install...
Nextcloud or one of the apps require upgrade - only >
You may use your browser or the occ upgrade command >

  Command "maintenance:install" is not defined.

Did you mean one of these?
      app:install
      maintenance:data-fingerprint
      maintenance:mimetype:update-db
      maintenance:mimetype:update-js
      maintenance:mode
      maintenance:repair
      maintenance:theme:update
      maintenance:update:htaccess

installing of nextcloud failed!
```

Any ideas? I didn't catch on to `stable-fpm-alpine` in time, I suppose.

**Comment by MiGoller** [comment] 2018-11-03 17:38
I have encountered the same error. Nextcloud will start but the Docker's entrypoint tries to install a few times; later on Nextcloud will be up and running.

If I do not provide environment variables for database setup, as I've done all the time up to 13.0.4, Nextcloud starts without any error messages.

Can anybody confirm that? It looks like the Nextcloud Docker container does not recognize that Nextcloud is already installed.

**Comment by weikinhuang** [comment] 2018-11-06 17:33
I am also seeing this upgrading from 14.0.0 to 14.0.3

**Comment by SnowMB** [comment] 2018-11-07 18:42
I can't really reproduce the issue. If you start the container, does it give you an installed version number?
Should start with something like this:

```
docker-compose logs -tf app
app_1  | 2018-11-07T18:36:13.906629237Z Initializing nextcloud 14.0.3.0 ...
app_1  | 2018-11-07T18:36:13.906661268Z Upgrading nextcloud from 13.0.7.2 ...
```

**Comment by weikinhuang** [comment] 2018-11-07 18:49
It thinks it's a new instance:

```
Initializing nextcloud 14.0.3.0 ...
Initializing finished
New nextcloud instance
Installing with MySQL database
starting nexcloud installation
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade


  Command "maintenance:install" is not defined.

  Did you mean one of these?
      app:install
      maintenance:data-fingerprint
      maintenance:mimetype:update-db
      maintenance:mimetype:update-js
      maintenance:mode
      maintenance:repair
      maintenance:theme:update
      maintenance:update:htaccess
```

My setup is using this container with kubernetes, so volume isn't persisted, only the data, plugins, and db

**Comment by MiGoller** [comment] 2018-11-07 19:20
If I provide the environment variables `MYSQL_*` when running `docker-compose` I receive the same log entries as @weikinhuang does. But without these environment variables my nextcloud container will start with such log entries.

```
$ docker logs 1........
Initializing nextcloud 13.0.7.2 ...
Initializing finished
New nextcloud instance
running web-based installer on first connect!
...
[Sun Nov 04 00:35:43.912141 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.11 configured -- resuming normal operations
[Sun Nov 04 00:35:43.912170 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

I do not persist `/var/www/html` as well; I just mount `/var/www/html/data`, `/var/www/html/config` and `/var/www/html/custom_apps` like I did in the past. The database is hold by a shared MariaDB server outside of the nextcloud stack.

Looks like the `docker-entrypoint.sh` script does not recognize that the upgrade from 13.0.4 to 13.0.7 already succeeded.

**Comment by wibbly13** [comment] 2019-06-30 09:10
To add to @MiGoller , I noticed this happens when you do a fresh installation but mount existing folders to `/var/www/html/data` and `/var/www/html/config`. By "existing folders" I mean folders that had previously been mounted to `/var/www/html/data` and `/var/www/html/config`, and contain valid data and config files.
`maintenance:install` runs OK if it's a totally fresh installation where mounts to `/var/www/html/data` and `/var/www/html/config` are clean.

**Comment by sebastiansterk** [comment] 2019-07-17 17:45
I'm also running into this issue with the latest nextcloud docker image ( nextcloud:latest which is nextcloud v16).
I deploy nextcloud in my k8s cluster, first deployment is fine, when redeploying it, I have the exact same issue mentioned in the first comment..

**Comment by tikoflano** [comment] 2019-08-14 18:25
I'm also having the problem when mounting only `/var/www/html/data`, `/var/www/html/config`, `/var/www/html/custom_apps` and `/var/www/html/themes`.

I remove the container with `docker-compose rm -sfv nextcloud`, si I think it might be related to deleting the volumes with the `-v` flag?

**Comment by robin-thoni** [comment] 2019-08-24 12:18
This happens when `installed` is set to `true` in `config/config.php`, which is obviously the case after the first installation.

Easy repro:

```
mkdir -p /tmp/nextcloud/config
chmod 777 /tmp/nextcloud/config
docker run -it -u www-data:www-data --entrypoint /bin/sh -v /tmp/nextcloud/config:/var/www/html/config nextcloud:16.0-apache -c bash
 NEXTCLOUD_UPDATE=1 /entrypoint.sh echo
 php occ maintenance:install --admin-pass=42 # This will succeed
 php occ maintenance:install --admin-pass=42 # This will fail with the reported error
 sed -i  "s/.*installed.*/  'installed' => false,/" config/config.php
 php occ maintenance:install --admin-pass=42 # This will fail because the admin user already exists, but the command is running
```

**Comment by mplx** [comment] 2019-12-27 15:53
If you just mount specific data directories like `/var/www/html/config` or `/var/www/html/data` you're missing the `/var/www/html/version.php` file which is checked in [line 38](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L38).

Thus `$installed_version` stays at its initialization value of `"0.0.0.0"`  and the entrypoint script thinks it's on a new installation ([line 50](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L50), [line 72](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L72)) - message "New nextcloud instance".

Now if you've set any database env variables (you likely will) it sets `install` to `true` (L92, L97, L102) and runs [`maintenance:install`](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L109) - which fails because `config/config.php` has set `installed` to `true` which suppresses the `maintenace:install` command ([register_command.php](https://github.com/nextcloud/server/blob/master/core/register_command.php#L68)): `Command is not defined`.

If you remove your database environment settings the container will run, however it will never be able to run the upgrade path ([line 134](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L134)) which might result in problems later on. Also removing database env still does an fresh copy ([rsync in L61](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L61)) and [preserves only some directories](https://github.com/nextcloud/docker/blob/master/upgrade.exclude) - i.e. previously installed apps like calendar or contacts will get wiped out.

So the *real* but non-satisfying solution is to map the full `/var/www/html/` directory outside your docker container until the container is able to deal with the situation of partly existing data directories properly.

**Closed as completed** 2023-03-28 14:32 UTC
