### ISSUE TITLE
Stuck in maintenance mode after switching to 14

### ISSUE THREAD

**Issue by schliflo** [nextcloud/docker#417] opened 2018-08-08 09:52 UTC
After switching to 14 and running `occ upgrade` in the container I'm stuck in maintenance mode with the following error:
```
InvalidArgumentException: Index name "oc_notes_meta"."notes_meta_file_id_user_id_index" is too long.
```

I wasn't sure where to report this (server, notes or here?)

**Comment by tilosp** [comment] 2018-08-08 10:35
Duplicate of nextcloud/server#10518

**Closed by tilosp** 2018-08-08 10:35 UTC
