### ISSUE TITLE
question: why server itself have to be installed after start container (aka. why server itself have to be persistenced)

### ISSUE THREAD

**Issue by bonjour-py** [nextcloud/docker#2241] opened 2024-06-18 17:15 UTC
i have a s3fs mountpoint to persistence data for my server , it makes the nextcloud server runs pretty slowly because lots of  IO reads.

if i just mount /var/www/html/data , it can not be reused after rebuild container

so i have this question writen in title  

and is there any possible to just mount /var/www/html/data

**Comment by joshtrichards** [comment] 2024-06-18 19:34
Duplicate of #2044

**Closed by joshtrichards** 2024-06-18 19:34 UTC
