### ISSUE TITLE
Running cron or occ on 15.0.7-apache impossible due to "empty" user

### ISSUE THREAD

**Issue by despens** [nextcloud/docker#719] opened 2019-04-19 05:27 UTC
Following advice by @J0WI, I want to set up cron jobs on my docker host rather than doing it inside the container. However, it seems impossible to do this with the latest docker image:

```console
$ docker exec -u www-data nextcloudserver_app_1 php cron.php
Console has to be executed with the same user as the web server is operated
Current user: www-data
Web server user: 
```

The "Web server user" name is empty, also nextcloud reports back an empty name on the admin page:

![image](https://user-images.githubusercontent.com/571494/56408332-3ebfdb00-6274-11e9-801d-5e12d7b2db22.png)

Checking inside the container, it looks like apache2 is run by www-data and root, however executing cron.php works with neither user.

```console
$ docker exec nextcloudserver_app_1 ps -uax
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.9 496428 34692 ?        Ss   Apr18   0:02 apache2 -DFOREGROUND
www-data    31  0.0  1.9 836916 73940 ?        S    Apr18   0:32 apache2 -DFOREGROUND
www-data    42  0.0  1.9 840784 75020 ?        S    Apr18   0:14 apache2 -DFOREGROUND
www-data   507  0.0  1.9 841032 72820 ?        S    Apr18   0:13 apache2 -DFOREGROUND
[...]
```

Adding the `docker exec` line to the host's crontab directly also didn't help.

It is also impossible to run any `occ` command due to the same issue:

```console
$ docker exec -u www-data nextcloudserver_app_1 php occ preview:generate-all -vvv
Console has to be executed with the user that owns the file config/config.php
Current user: www-data
Owner of config.php: 
```

---

The problem persists with the the [full-apache](https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/full/apache) container, the cron job assigned to busybox crond isn't executed.

```console
$ docker exec -u www-data nextcloudserver_app_1 php cron.php
Console has to be executed with the same user as the web server is operated
Current user: www-data
Web server user: 
$ docker exec nextcloudserver_app_1 cat /var/spool/cron/crontabs/www-data
*/15 * * * * php -f /var/www/html/cron.php
```

What could be the issue here?

**Comment by despens** [comment] 2019-04-19 21:00
I have now built the "full" apache container including busybox crond. Inside the container the same effect happens and the cron ist not executed: the user running the web server is an empty string.

```console
root@ff60e6b0dd20:/# cat /var/spool/cron/crontabs/www-data 
*/15 * * * * php -f /var/www/html/cron.php
root@ff60e6b0dd20:/# php -f /var/www/html/cron.php
Console has to be executed with the same user as the web server is operated
Current user: root
Web server user: 
root@ff60e6b0dd20:/# 
```

**Comment by despens** [comment] 2019-04-20 12:04
This bug also makes it impossible to run certain database maintenance tasks, such as [updating tables to 64bit int and creating indices](https://docs.nextcloud.com/server/15/admin_manual/configuration_database/bigint_identifiers.html).

**Comment by J0WI** [comment] 2019-04-20 14:55
I'm not able to reproduce this. Have you verified the permissions in `/var/www/html/`?

**Comment by despens** [comment] 2019-04-20 17:49
They look like this, seems good to me:

```console
$ docker exec nextcloudserver_app_1 ls -la /var/www/html
total 168
drwxrwxrwx 15 www-data root  4096 Apr 16 15:14 .
drwxrwxr-x  1 www-data root  4096 Apr 20 14:58 ..
-rw-r--r--  1 www-data root  4126 Apr 17 13:17 .htaccess
-rw-r--r--  1 www-data root   163 Apr 17 13:17 .user.ini
drwxr-xr-x 32 www-data root  4096 Apr 16 15:14 3rdparty
-rw-r--r--  1 www-data root 12063 Apr 16 15:14 AUTHORS
-rw-r--r--  1 www-data root 34520 Apr 16 15:14 COPYING
drwxr-xr-x 38 www-data root  4096 Apr 16 15:14 apps
drwxr-xr-x  2 www-data root  4096 Apr 16 15:14 config
-rw-r--r--  1 www-data root  3650 Apr 16 15:14 console.php
drwxr-xr-x 18 www-data root  4096 Apr 16 15:14 core
-rw-r--r--  1 www-data root  4979 Apr 16 15:14 cron.php
drwxr-xr-x 16 www-data root  4096 Apr 20 14:53 custom_apps
drwxrwx---  6 www-data root  4096 Apr 17 14:28 data
-rw-r--r--  1 www-data root   156 Apr 16 15:14 index.html
-rw-r--r--  1 www-data root  3172 Apr 16 15:14 index.php
drwxr-xr-x  6 www-data root  4096 Apr 16 15:14 lib
-rwxr-xr-x  1 www-data root   283 Apr 16 15:14 occ
drwxr-xr-x  2 www-data root  4096 Apr 16 15:14 ocm-provider
drwxr-xr-x  2 www-data root  4096 Apr 16 15:14 ocs
drwxr-xr-x  2 www-data root  4096 Apr 16 15:14 ocs-provider
-rw-r--r--  1 www-data root  2951 Apr 16 15:14 public.php
-rw-r--r--  1 www-data root  5139 Apr 16 15:14 remote.php
drwxr-xr-x  4 www-data root  4096 Apr 16 15:14 resources
-rw-r--r--  1 www-data root    26 Apr 16 15:14 robots.txt
drwxr-xr-x 12 www-data root  4096 Apr 16 15:14 settings
-rw-r--r--  1 www-data root  2232 Apr 16 15:14 status.php
drwxr-xr-x  3 www-data root  4096 Apr 16 15:14 themes
-rw-r--r--  1 www-data root   362 Apr 16 15:14 version.php
```

Could this be an issue with the docker image `nextcloud:15.0.7-apache`? It almost seems as if php is unable to stat the required ownership info?

**Comment by despens** [comment] 2019-04-28 19:24
The cronjob can now be executed when I made config.php writable to nextcloud: Instead of mapping a full-length outside config.php file into the docker, I am mapping in config files containing only the settings that I need to make. See https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file

**Comment by LitvK** [comment] 2019-05-19 13:29
I have the same issue. The only one solution I've found is to run
`docker exec --user www-data nextcloud php cron.php`
at host machine by cron.

**Comment by despens** [comment] 2019-05-19 16:56
@LitvK that's the recommended way to do it.

**Comment by J0WI** [comment] 2020-06-05 14:55
I'm closing this because it mentions a specific version that is EOL.

**Closed by J0WI** 2020-06-05 14:55 UTC
