### ISSUE TITLE
"Set your password"/welcome email not displayed correct in another language (german)

### ISSUE THREAD

**Issue by konwin** [nextcloud/docker#815] opened 2019-07-23 07:53 UTC
Hello,
I'm using Nextcloud with the config.php options
`  'default_language' => 'de',`
and
`  'default_locale' => 'de',`
and I think there is something wrong with the template for the "Set your password" mail.
The size of the button for "Set your password" = "Setze dein Kennwort" in german does not scale right for the 2-line german translation!
The button for "Install client" does scale the right way for the 2-line german translation, so maybe just copy the properties of the "Install client" button to the "Set your password" button?

![WELCOME](https://user-images.githubusercontent.com/44242369/61693123-48ebec80-ad2f-11e9-9821-5e5359c38acf.png)
I tried different mail providers and mail/web clients to eliminate this as the reason.

**Comment by J0WI** [comment] 2019-07-23 23:12
Duplicate of https://github.com/nextcloud/server/issues/13287

**Closed by J0WI** 2019-07-23 23:12 UTC
