### ISSUE TITLE
IMAP user_backend fails

### ISSUE THREAD

**Issue by meghadeep-com** [nextcloud/docker#1418] opened 2021-02-21 05:46 UTC
After the version 21 update, IMAP user_backend with Dovecot IMAP server fails.

I have this in my config.php

'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => 'mail.domain.tld',
        1 => 993,
        2 => 'ssl',
        3 => '',
      ),
    ),
  ),

**Comment by Aaron-Ritter** [comment] 2021-02-25 10:40
its likely because the App "External user authentication" is not updated / enabled.

**Comment by J0WI** [comment] 2021-02-25 15:17
Duplicate of https://github.com/nextcloud/user_external/issues/171

**Closed by J0WI** 2021-02-25 15:17 UTC

**Comment by almereyda** [comment] 2021-04-03 01:32
I am not sure if this is actually a duplicate. Concerning the breaking of the external users IMAP logins, yes.

But concerning an application image that is usually upgraded with simply pulling `latest` and then recreating its containers, maybe no?

I wonder if we can have a pre-upgrade check in the image for compatibility of plugin updates to the next version, and stop before migrating the database, if there are breaking changes. Or create a paranoid mode with an environmental variable set, that will make sure not to upgrade, and output the reason why so, if some of the currently enabled plugins wouldn't make it.

Not everybody has the infrastructure available to create a clone of the application to test-drive upgrades, and some might not have an up to date backup of their data, to which they could roll back to.

Would that instead qualify for a new issue, or reopening here?
