### ISSUE TITLE
NEXTCLOUD_TABLE_PREFIX not behaving as expected

### ISSUE THREAD

**Issue by Windyo** [nextcloud/docker#776] opened 2019-06-15 11:48 UTC
I set `NEXTCLOUD_TABLE_PREFIX=oc_` in my db.env to migrate an old installation to docker.
It didn't work so I added it in the Compose file - still no gucci, config.php shows `'dbtableprefix' => '',`

**Comment by J0WI** [comment] 2019-06-18 21:50
> To enable auto configuration, set your database connection via the following environment variables.

https://github.com/nextcloud/docker#auto-configuration-via-environment-variables

Just setting `NEXTCLOUD_TABLE_PREFIX` has no effect.

**Comment by Windyo** [comment] 2019-06-18 21:54
Yeah I did that as well. Full db.env is;

```MYSQL_DATABASE=nc
MYSQL_USER=<redacted>
MYSQL_PASSWORD=<redacted>
MYSQL_ROOT_PASSWORD=<redacted>
NEXTCLOUD_TRUSTED_DOMAINS=<redacted>
NEXTCLOUD_DATA_DIR=/home
NEXTCLOUD_TABLE_PREFIX=oc_```

Still doesn't set it automatically tho.

**Comment by J0WI** [comment] 2019-06-21 22:18
I'm not able to reproduce this. Do you already have a configuration in an attached volume?

**Comment by Windyo** [comment] 2019-06-22 11:11
No - I didn't find a way to map only part of /var/www/html to a volume, so I ended up migrating datadir to /home/ and use a bind mount for that, while actually using the recommended Nextcloud volume for /var/www/html.

I just tried destroying the volume to see - same problem. Interestingly enough Nextcloud also doesn't understand that it's already set up and requires me to set up an Admin account that already exists, though that's another discussion entirely.

**Comment by J0WI** [comment] 2019-06-22 16:16
Mount `/var/www/html/config` before `/var/www/html`.

> Interestingly enough Nextcloud also doesn't understand that it's already set up and requires me to set up an Admin account that already exists, though that's another discussion entirely.

That's expected, because `'installed' => true,` is not set anymore.

**Comment by Windyo** [comment] 2019-06-22 16:30
Oh.

Then I guess both issues are a case of user error. Thanks I'll try this out. I guess we can close this.

Anon

________________________________

**Comment by Windyo** [comment] 2019-06-22 19:04
follow-up - is thre an env-var for `installed` ?

**Comment by J0WI** [comment] 2019-06-22 19:08
No.

**Comment by Windyo** [comment] 2019-06-22 19:18
Alright thanks

Anon

________________________________

**Comment by rubo77** [comment] 2020-05-15 10:15
It seems like it is impossible to install the docker Nextcloud without `oc_` as prefix.

I used this in my docker-compose.yaml:
```
services:
  db:
    image: mariadb
    #?command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /var/kunden/docker-services/next-dev.eclabs.de/volumes/mysql:/var/lib/mysql
    environment:

      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_PASSWORD=***
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_TABLE_PREFIX=""

But still, it installed with the prefix `oc_`

**Comment by rubo77** [comment] 2020-05-16 01:04
I also tried using the `db.env` file for the variables, still the prefix is ignored.

also tried `nc_` as prefix. Still it installs `oc_` as prefix

**Comment by J0WI** [comment] 2020-06-05 15:32
https://github.com/nextcloud/server/pull/21112
https://github.com/nextcloud/docker/pull/1131

**Closed** 2020-06-05 23:37 UTC
Labels: question
