### ISSUE TITLE
Does not have freetype support?

### ISSUE THREAD

**Issue by ddyllen-z** [nextcloud/docker#255] opened 2018-02-08 11:32 UTC
`Error: Call to undefined function OC\imagettfbbox()`

Another error.The following error will occur when visit address `/apps/files_trashbin/ajax/preview.php` or `/core/preview.png?file=....`:
```shell
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
[Thu Feb 08 03:04:55.623000 2018] [mpm_prefork:error] [pid 1] (12)Cannot allocate memory: AH00159: fork: Unable to fork new process
```
The error will crash the mysql server.And there are no errors in the mysql log.

**Comment by tilosp** [comment] 2018-02-08 11:45
Duplicate of #248

**Closed by tilosp** 2018-02-08 11:45 UTC
