### ISSUE TITLE
Docker Secrets for NEXTCLOUD_ADMIN_PASSWORD 

### ISSUE THREAD

**Issue by RGregat** [nextcloud/docker#235] opened 2018-01-29 09:33 UTC
Is there a way to use a Docker Secret as the password for the NEXTCLOUD_ADMIN_PASSWORD environment variable?

I tried it with a start.sh Skript to read the secret file and set it to the environment variable NEXTCLOUD_ADMIN_PASSWORD. After that i start supervisord. 

Probably i'm wrong, but supervisord should take care to start apache and with that the nextcloud service. That mean there should be no problem to set the password in a Shell-Skript and not in a docker-compose.yml?

**start.sh:**
```
#! /bin/bash

unset NEXTCLOUD_ADMIN_PASSWORD
# lesen des Passworts aus den Secrets
userpassword_file="/run/secrets/userpassword_kunde"

if [ -f $userpassword_file ]; then
	NEXTCLOUD_ADMIN_PASSWORD=$(cat $userpassword_file)
else
	# password file not set
	exit 1
fi

echo $NEXTCLOUD_ADMIN_USER
echo $NEXTCLOUD_ADMIN_PASSWORD

chown -R www-data:root /var/www/html

exec /usr/bin/supervisord
```

**supervisord.conf:**
```
[supervisord]
nodaemon=true
logfile=/var/log/supervisord/supervisord.log
pidfile=/var/run/supervisord/supervisord.pid
childlogdir=/var/log/supervisord/
logfile_maxbytes=50MB                           ; maximum size of logfile before rotation
logfile_backups=10                              ; number of backed up logfiles
loglevel=error

[program:apache2]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
command=apache2-foreground
```

**Comment by martianrock** [comment] 2018-02-22 13:31
did you try:
`export NEXTCLOUD_ADMIN_PASSWORD`
before last line exec
or:
`exec env NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD /usr/bin/supervisord`
or:
`NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD exec /usr/bin/supervisord`
?

**Comment by skwee** [comment] 2018-04-04 12:05
Looking at Version 13.0.1:/usr/src/nextcloud/config/autoconfig.php
would it not be a better idea to it would be a good idea to do without environment variables and fetch the secrets directly from /run/secrets/...
To keep things flexible one could use the env-vars as keys / paths to the secrets

**Comment by tilosp** [comment] 2018-08-24 13:37
Duplicate of #385

**Closed by tilosp** 2018-08-24 13:37 UTC
Labels: help wanted
