### ISSUE TITLE
Cannot sign in, client hangs after entering URL

### ISSUE THREAD

**Issue by Yournished** [nextcloud/docker#761] opened 2019-05-25 12:14 UTC
I am running the fpm/redis docker-compose image of Nextcloud 16.0.1.1. My nextcloud sync client is 2.5.1git on debian 9 stable.

When I try to add an account to sync, after I enter the URL and click next, I get a white screen and a blue horizontal line (progress bar?) on top. Next is grayed out and it seems stuck like that indefinitely.

I can however access my nextcloud webUI through a browser (typing the same URL) and see my files and so on.

Strangely enough, I managed to add an account earlier, I believe I used the 2.5.3 appimage while I was still on Nextcloud 13 (I upgraded since then). That image now also fails to add the account. But the account that is already active can sync without problem.

**Comment by J0WI** [comment] 2021-02-19 15:00
Duplicate of #665

**Closed by J0WI** 2021-02-19 15:00 UTC
