### ISSUE TITLE
Database Incompatibility with MariaDB 10.6.0

### ISSUE THREAD

**Issue by Wibias** [nextcloud/docker#1492] opened 2021-05-07 18:21 UTC
Hey!

So I updated mariadb, which I use with nextcloud to version alpha 10.6.0.
Which this verison this came [https://mariadb.com/kb/en/innodb-system-variables/#innodb_read_only_compressed](url) and gave me this error:
![image](https://user-images.githubusercontent.com/37517432/117492381-d256c800-af71-11eb-9dac-22c4b53fa106.png)
To fix this I needed to add `command: --innodb-read-only-compressed=OFF` to my mariadb docker compose.
Just a head up when mariadb 10.6.0 becomes the stable version and anyone else get this problem.

**Comment by UbioZur** [comment] 2021-06-14 07:11
Thank you for the work around.
I was stuck on that problem trying to install nextcloud and mariadb 10.6.1

**Comment by mreho** [comment] 2021-07-13 08:06
Working perfectly fine, you made me save a couple of hours, thank you :smile:

**Comment by LukBukkit** [comment] 2021-07-14 08:58
MariaDB 10.6.3 has been published under the `latest` tag on [Docker Hub](https://hub.docker.com/_/mariadb). My setup broke last night as I've upgrading all my images at midnight. I guess a lot of other installations are to follow. The work around did help, but how can me make sure, that people find it?

**Comment by mklemme1** [comment] 2021-07-14 15:29
> MariaDB 10.6.3 has been published under the `latest` tag on [Docker Hub](https://hub.docker.com/_/mariadb). My setup broke last night as I've upgrading all my images at midnight. I guess a lot of other installations are to follow. The work around did help, but how can me make sure, that people find it?

Same here!
I changed `docker-compose` like this:

```
services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
    restart: unless-stopped
```

Still, I suggest that the Nextcloud team develops an update fix that changes the `ROW_FORMAT` in the database.

**Comment by UbioZur** [comment] 2021-07-15 01:31
> how can we make sure, that people find it?

By adding it to the documentation (https://github.com/nextcloud/docker#using-an-external-database) as a short term solution.
At least it should cover more people to be aware of the solution.

**Comment by rumbleh** [comment] 2021-07-15 12:32
I can confirm: add innodb_read_only_compressed = 0 inside my MariaDB conf file. 

In my case was 50-server.cnf 

and everything worked like a charm!

**Comment by Phlogi** [comment] 2021-07-16 06:41
From MariaDB 10.6.0, tables that are of the COMPRESSED row format are read-only by default. This is the first step towards removing write support and deprecating the feature.

Set the innodb_read_only_compressed variable to OFF to make the tables writable.

So this is not going to last that long. 

You need to change your tables, nextcloud does not do this for you.

Create the multiple ALTER statements with:

```SELECT CONCAT('ALTER TABLE `', table_name, '` ROW_FORMAT=dynamic;') AS aQuery
FROM information_schema.tables
WHERE table_schema = 'nextcloud'```

Then execute those in a  second step.

**Comment by Wibias** [comment] 2021-07-16 17:36
https://github.com/nextcloud/docker/issues/1536

**Comment by J0WI** [comment] 2021-07-18 21:57
Closing as duplicate of https://github.com/nextcloud/server/issues/25436 and https://github.com/nextcloud/docker/issues/1536

**Closed by J0WI** 2021-07-18 21:57 UTC

**Comment by jfabaf** [comment] 2021-07-21 16:24
> > MariaDB 10.6.3 has been published under the `latest` tag on [Docker Hub](https://hub.docker.com/_/mariadb). My setup broke last night as I've upgrading all my images at midnight. I guess a lot of other installations are to follow. The work around did help, but how can me make sure, that people find it?
> 
> Same here!
> I changed `docker-compose` like this:
> 
> ```
> services:
>   nextcloud-db:
>     image: mariadb
>     container_name: nextcloud-db
>     command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
>     restart: unless-stopped
> ```
> 
> Still, I suggest that the Nextcloud team develops an update fix that changes the `ROW_FORMAT` in the database.

Thank you very much! 
I added this line:
 command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
And now it works perfectly

**Comment by KurtCa** [comment] 2021-08-09 12:45
Change ROW_FORMAT from COMPRESSED to DYNAMIC.

USE INFORMATION_SCHEMA;
SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA,"`.`", TABLE_NAME, "` ROW_FORMAT=DYNAMIC;") AS MySQLCMD FROM TABLES WHERE TABLE_SCHEMA = "nextcloud";

This will return an SQL command for each table in the nextcloud database. 
You can use these commands to alter all the tables.

After this you can set the innodb-read-only-compressed back to the default "ON"

INFO: [https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier](https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier)

**Comment by henrywithu** [comment] 2021-09-02 02:59
> > MariaDB 10.6.3 has been published under the `latest` tag on [Docker Hub](https://hub.docker.com/_/mariadb). My setup broke last night as I've upgrading all my images at midnight. I guess a lot of other installations are to follow. The work around did help, but how can me make sure, that people find it?
> 
> Same here!
> I changed `docker-compose` like this:
> 
> ```
> services:
>   nextcloud-db:
>     image: mariadb
>     container_name: nextcloud-db
>     command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
>     restart: unless-stopped
> ```
> 
> Still, I suggest that the Nextcloud team develops an update fix that changes the `ROW_FORMAT` in the database.

This works perfectly. Thanks @mklemme1

**Comment by leschard** [comment] 2023-09-02 10:53
**Useful update: the incompatibility disappears with MariaDB 10.6.6 and above**. 

(The current latest patch release is 10.6.15, so far above.)
Successfully tested on my side.

Doc from MariaDB:
> InnoDB COMPRESSED Row Format
> From [MariaDB 10.6.0](https://mariadb.com/kb/en/mariadb-1060-release-notes/) until [MariaDB 10.6.5](https://mariadb.com/kb/en/mariadb-1065-release-notes/), tables that are of the COMPRESSED row format are read-only by default. This was intended to be the first step towards removing write support and deprecating the feature.

> This plan has been scrapped, and from [MariaDB 10.6.6](https://mariadb.com/kb/en/mariadb-1066-release-notes/), COMPRESSED tables are no longer read-only by default.
 
Source: https://mariadb.com/kb/en/upgrading-from-mariadb-10-5-to-mariadb-10-6/
