### ISSUE TITLE
Please update dockerhub images for 14.0.1 as well...

### ISSUE THREAD

**Issue by kratan** [nextcloud/docker#472] opened 2018-09-28 08:17 UTC
Hi,
on https://hub.docker.com/_/nextcloud/ there are still RC images for nextcloud, please update

greets

**Comment by RouL** [comment] 2018-09-28 08:52
Also waiting for that.

**Comment by tilosp** [comment] 2018-09-28 10:51
Duplicate of #470

**Closed by tilosp** 2018-09-28 10:51 UTC
