### ISSUE TITLE
Legacy encryption in nextcloud docker 

### ISSUE THREAD

**Issue by Pushergene** [nextcloud/docker#1292] opened 2020-10-28 09:17 UTC
Since nc 20 i get a message that my encryption is old. Wgat should i do? Do i have to worry that my nextcloud gets broken after some patches? The documentation of that message doesnt explain the fix for docker

**Comment by Kuphi** [comment] 2020-11-20 08:01
Same question. What are the differences between legacy and current encryption?

Maybe this document can give some answers: https://eprint.iacr.org/2020/1439.pdf

**Comment by Kuphi** [comment] 2020-11-20 08:22
> Since nc 20 i get a message that my encryption is old. Wgat should i do? Do i have to worry that my nextcloud gets broken after some patches? The documentation of that message doesnt explain the fix for docker

This does not only affect docker images. I created a feature request in the git of nextcloud/server:
https://github.com/nextcloud/server/issues/24240

**Comment by J0WI** [comment] 2021-02-19 15:23
Duplicate of nextcloud/server#24240

**Closed by J0WI** 2021-02-19 15:23 UTC
Labels: question
