### ISSUE TITLE
Collabora in docker compose does not work

### ISSUE THREAD

**Issue by biocyberman** [nextcloud/docker#241] opened 2018-02-02 15:53 UTC
I have all containers in `docker-compose.yml` up and running. But the Collabora feature does not work. I tried chaning setting in `https://<localhost>/index.php/settings/admin/richdocuments` to something like: `https://collabora` but I did not work neither. 

I got this error: 
```
Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.


Technical details
Remote Address: 172.19.0.5
Request ID: RNMTptetgjuvzy2sve2P
```

Going into `https://<localhost>/index.php/settings/admin/logging` I saw this:

```
Error | richdocuments | GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to collabora port 443: Connection refused | 2018-02-02T16:44:31+0100

```
After changing collabora path to `https://collabora:9980` I got this:
`GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain`

**Comment by biocyberman** [comment] 2018-02-02 16:54
Guess I have to disabled `https` or certificate verification in `collabora`  image which uses curl (http://flwebsites.biz/posts/how-fix-curl-error-60-ssl-issue). I prefer the later but don't know how to do that

**Comment by camhunt** [comment] 2018-10-09 21:20
@biocyberman I was able to use Snowyo's docker-compose [snippet](https://help.nextcloud.com/t/collabora-configuration-with-docker-compose/3970) to work using the official NextCloud docker-compose file.

**Comment by aaronSkar** [comment] 2019-01-28 23:50
@biocyberman you should look into using let's encrypt to get signed certs for you collabora office and nextcloud instance.  The best way to do this is with a rev proxy (nginix).  Once you have done that you will need to use your domain name used for the lets encrypt cert in the collabora office settings menu within nextcloud.  So where you are putting https://collabora:9980 you would just use https://collabora.your.domain.here.

**Comment by J0WI** [comment] 2019-06-14 12:19
There's an example at https://github.com/nextcloud/docker/pull/630
Closing as duplicate of #223

**Closed by J0WI** 2019-06-14 12:19 UTC
