### ISSUE TITLE
Nextcloud Bruteforce protection issue with Nginx reverse proxy from the official examples

### ISSUE THREAD

**Issue by MegadoomerX** [nextcloud/docker#2056] opened 2023-08-12 11:23 UTC
I'm experiencing some major difficulties with the Bruteforce protection module in combination with an Nginx reverse proxy container (as taken from the docker-compose examples). 
 
Whenever a user is changing their password without updating their auto-sync apps, the message "We have detected multiple invalid login attempts from your IP. Therefore your next login is throttled up to 30 seconds." will appear on the login prompt for **everyone**. 
 
If this state persists and the user forgets to update their mobile clients/talk apps, any login will become impossible from any location and any account with the error message "Too many requests", effectively causing a DoS event. 
 
I _believe_ the reason for this is that Nextcloud only sees the internal IP of the Ngnix container and all user logins are convoluted within that IP address so that one failed login counts for all users. 
 
This makes Bruteforce protection either a potential DoS-risk or useless, because whitelisting the Nginx IP means effectively disabling it altogether. 
 
Is there any way to solve this, to keep the security feature intact?

**Comment by meonkeys** [comment] 2023-08-12 19:09
You can use `RemoteIPInternalProxy`. See <https://help.nextcloud.com/t/apache-docker-behind-reverse-proxy/151754>. This isn't related to the Nextcloud community Docker image.

**Comment by joshtrichards** [comment] 2023-08-13 13:49
@MegadoomerX Did you see the NC documentation? This is specifically discussed along with what to do:

- https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html?highlight=trusted_proxies
- https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=trusted_proxies

**Comment by joshtrichards** [comment] 2023-11-04 16:33
Follow-up: My apologies, @MegadoomerX. This was ultimately a duplicate of #1103 and got fixed #2004 about a week after your report. :)

**Closed by joshtrichards** 2023-11-04 16:33 UTC
Labels: question, examples, needs info, integration: proxy
