### ISSUE TITLE
Problem using private IPs for clients accessing Nextcloud

### ISSUE THREAD

**Issue by hack-char** [nextcloud/docker#1875] opened 2022-12-06 18:25 UTC
https://github.com/nextcloud/docker/blob/6103e074d81396c235fb453a88f518104cf35382/25/apache/Dockerfile#L120-L122

The Apache directive "RemoteIPTrustedProxy" will ignore a remote host that has a private IP. All of my clients accessing Nextcloud use a private IP. My configuration requires this to be RemoteIPInternalProxy. Please either make this selectable or default to 'internal'.
As a work-around, I am mounting a modified remoteip.conf file with my exact proxy IP using this RemoteIPInternalProxy directive.

**Comment by meonkeys** [comment] 2023-02-24 05:23
Related, I think: <https://help.nextcloud.com/t/apache-docker-behind-reverse-proxy/151754>

**Comment by joshtrichards** [comment] 2023-11-04 16:30
Duplicate of #1103 and fixed by #2004.

**Closed by joshtrichards** 2023-11-04 16:30 UTC
Labels: enhancement, feature: auto config (environment variables), integration: proxy
