### ISSUE TITLE
Social sharing via email cannot be installed in Nextcloud 15

### ISSUE THREAD

**Issue by gdudas** [nextcloud/docker#580] opened 2018-12-12 21:54 UTC
When I try to install "Social sharing via email" application in Nextcloud 15.0.0, I got this message:

> This app cannot be installed because the following dependencies Social sharing via email are not fulfilled:Server version 14 or lower is required

**Comment by J0WI** [comment] 2018-12-12 22:20
This is not related to Docker. Closing as duplicate of https://github.com/nextcloud/socialsharing/issues/27

**Closed by J0WI** 2018-12-12 22:20 UTC
Labels: duplicate
