### ISSUE TITLE
fpm version 16.0.2 not available?

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/docker#805] opened 2019-07-09 05:55 UTC
a `docker-compose pull` is still pulling the 16.0.1 version and not the 16.0.2 version.
Also other users did already left notes under https://hub.docker.com/_/nextcloud/?tab=reviews 
I urgently would need the 16.0.2 fpm version since I did an update via the web updater two days ago on 16.0.2 but I had to restart the container yesterday and now even after a docker-compose pull I do get `Can't start Nextcloud because the version of the data (16.0.2.1) is higher than the docker image version (16.0.1.1) and downgrading is not supported. Are you sure you have pulled the newest image version?`

**Comment by OverByThere** [comment] 2019-07-09 14:09
This is currently in progress here: https://github.com/docker-library/official-images/pull/6236. Also possible duplicate of #802

**Comment by GuidoDr** [comment] 2019-07-09 14:16
16.0.3 was just released by Nextcloud, so hopefully it will then already be the 16.0.3 release ;-)
So nothing I can do right now in order to get our instance up and running again besides just to sit and wait for the docker image.

**Comment by OverByThere** [comment] 2019-07-09 14:21
There's a possibility (I cant check myself) that you could change the version number in the `version.php`, as that's what docker uses to reference.. but there's no guarantee this'll work (or break anything), and only works if you are using a different `/var/www/html` folder.

As mentioned on the other issue, I think its an problem with the testing there, so hopefully they'll add and it'll get released soon.

**Comment by GuidoDr** [comment] 2019-07-09 14:26
> could change the version number in the version.php
I tried this already yesterday. This brought me only one step further, the error message of the log file is then shown on the webpage ;-) 
Never mind, I will wait and next time I will not use the web updater anymore, before the image is ready.

**Comment by OverByThere** [comment] 2019-07-09 15:02
I added this line to the bottom of my `version.php` which seems to have fixed it for me:

```if(!http_response_code()) { $OC_Version = array(16,0,1,1); }```
What this'll do is report version 16.0.1.1 if the PHP script is run in [command line](https://stackoverflow.com/a/42247484/2076229) format, and 16.0.2.1 if running normally.

This has worked for me, but cannot guarantee what this may do in the future.

**Comment by GuidoDr** [comment] 2019-07-09 15:06
great thanks, also works here ;-)

**Closed** 2019-07-09 15:06 UTC
