### ISSUE TITLE
Remove index.php from URLs

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/docker#1186] opened 2020-07-22 02:52 UTC
It would be great if Apache was configured so that index.php was removed from URLs, like when using php-fpm on NGINX

**Comment by J0WI** [comment] 2020-11-07 01:20
I guess this is a duplicate of https://github.com/nextcloud/server/issues/16764

**Comment by thomas-mc-work** [comment] 2023-02-09 10:08
I think nextcloud/server#16764 is only about enabling it per default. It can still be configured manually per instance: https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls

**Comment by thomas-mc-work** [comment] 2023-02-09 13:57
It seems to be configured like that: https://github.com/nextcloud/docker/search?q=RewriteBase

Did you add the instructions in your `config.php` according to the documentation?

**Comment by joshtrichards** [comment] 2023-10-21 16:17
@seanthegeek I'm confused by your request as that's already been the default behavior of the Apache-based Docker since 2017 via #152. I'm going to close this since your request seems to be a configuration problem and pretty URLs work on all installations I have access to. Feel free to follow-up here if you think there's a bug or at the Nextcloud Help Forum (https://help.nextcloud.com) if you need help troubleshooting your configuration.

@J0WI I think since it's been the Docker image's implemented behavior since #152 we're probably better offleaving it even if it remains not the upstream default.

**Closed by joshtrichards** 2023-10-21 16:17 UTC
Labels: bug
