### ISSUE TITLE
I just want to be able to use traefik as a reverseproxy

### ISSUE THREAD

**Issue by Motophan** [nextcloud/docker#1116] opened 2020-05-10 12:53 UTC
And dont understand multiple service routing tables or anything like that. Documentation is lacking on this.

Can you just fix it so I can put an enviroment variable that will make it so nextcloud will trust my reverseproxy.

like `-e DOCKER_REVERSE_PROXY=TRUE`
and then the standard lables would work that everyone uses
```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-rtr.entrypoints=https"
      - "traefik.http.routers.nextcloud-rtr.rule=Host(`nextcloud.$DOMAINNAME`)"
      - "traefik.http.routers.nextcloud-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.freepbx.middlewares=chain-basic-auth@file"
      ## HTTP Services
      - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=443"
```
Nearly everyone who has a home server uses these because they are modular. the only diffrence is they may use a middleware for a authorization token like 
```
      - "traefik.http.routers.nextcloud.middlewares=chain-basic-auth@file"
```

**Comment by zicklag** [comment] 2020-05-15 19:10
Here are instructions for how to trust the reverse proxy: https://docs.nextcloud.com/server/18/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse%20proxy#reverse-proxy.

**Comment by joshtrichards** [comment] 2023-10-23 17:16
Duplicate of #1061 

Also, see the `TRUSTED_PROXIES` parameter.

**Closed by joshtrichards** 2023-10-23 17:16 UTC
Labels: enhancement
