### ISSUE TITLE
overwrite protocol

### ISSUE THREAD

**Issue by fractalf** [nextcloud/docker#851] opened 2019-09-01 17:10 UTC
There are problems logging in with the iOS app which requires one to set `'overwriteprotocol' => 'https'` in the config.php (ref: https://github.com/nextcloud/ios/issues/768)

Is there any way of putting this into a `.env` constant for docker-compose or something?
The fix right now is basically connecting to the container, installing vim and edit manually.

Thanks

**Comment by SnowMB** [comment] 2019-09-04 07:56
There's work on it. See #819.

**Comment by J0WI** [comment] 2019-10-03 12:11
Duplicate of #742

**Closed by J0WI** 2019-10-03 12:11 UTC
Labels: enhancement, image
