### ISSUE TITLE
docker image cannot be associated with external datasource

### ISSUE THREAD

**Issue by share1001** [nextcloud/docker#1898] opened 2023-01-17 01:35 UTC
The docker image of nextcloud runs independently, and there is no problem if it is not associated with the external database. However, if you use docker-compose or docker-link to associate with the database, an error will be reported and the docker log is as follows:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 16 16:04:23.284396 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.14 configured -- resuming normal operations
[Mon Jan 16 16:04:23.284472 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'172.17.0.1 - - [16/Jan/2023:16:57:34 +0000] "GET /core/img/app-background.jpg HTTP/1.0" 200 190778 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
```

docker-compose.yml
```
version: '3.5'

services:
  db_nextcloud:
    container_name: db_nextcloud
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW    
    networks:
      cloudnetwork: 
        ipv4_address: 172.19.0.5
    volumes:
      - "./db:/var/lib/mysql"       #./db是数据库持久化目录，可以修改
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: nextcloud!@
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud!@
    restart: always
    
  nextcloud:
    container_name: nextcloud
    image: nextcloud:25.0.2
    networks: 
      cloudnetwork: 
    ports:
      - 8061:80
      - 4433:443
    depends_on:
      - db_nextcloud
    volumes:
      - "./data:/var/www/html"      #./data是数据位置，可以修改
    restart: always
    command: ["apache2-foreground "]
networks:
  cloudnetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
```
This script can run normally before nextcloud version 23, but version 25 cannot run normally, and the above error is reported

**Comment by meonkeys** [comment] 2023-01-17 07:27
I'm having trouble reading your `docker-compose.yml` file. Will you fence your code samples with three backticks so it is rendered with a fixed-width font?

**Comment by meonkeys** [comment] 2023-01-17 08:11
I'm suggesting you fence your code so it is easier to read. Check out https://github.github.com/gfm/#fenced-code-blocks ... just use three backticks above and below the text of `docker-compose.yml`.

Example:

```
blah
  foo
bar
```

**Comment by joshtrichards** [comment] 2023-07-21 21:14
Hi @share1001 - Thanks for the report. Unfortunately it's not clear what the problem is from your report as-is.  Lots of people define their db in the same compose - it's probably more common than not doing so. I'm doing it across probably >10 stacks.

> The docker image of nextcloud runs independently, and there is no problem if it is not associated with the external database. However, if you use docker-compose or docker-link to associate with the database, an error will be reported and the docker log is as follows:

The `AH00558` is informational only and doesn't prevent Apache from operating. If you want it to go away you need to define DNS for the IP address assigned to your Docker container. However that is highly unlikely to be related to your reported problem. For the record, most of my stacks generate that warning from Apache and work just fine.

Can you provide some insight into what behavior you experienced?  i.e what, precisely, did not seem to be working? 

With the Compose file you provided I can't reproduce your issue because it lacks environment variables for your nextcloud app container. So I have to assume you manually defined those parameters and thus I can't possibly replicate your situation fully.

> This script can run normally before nextcloud version 23, but version 25 cannot run normally, and the above error is reported

Can you provide the exact compose file you used that did *not* have problems? Also, again, if you want us to try to reproduce this you'll need to provide the rest of the context of your NC configuration (i.e. the output of `./occ config:list system`)  since you seem to not be configuring Nextcloud via your Compose file. I also suspect the real clues to whatever is going on will be in your `nextcloud.log`. 

My guess is there is some incongruity in your Nextcloud `dbhost` parameters under the two different scenarios, but that's a wild guess.

Please attempt to reproduce the problem, check your `nextcloud.log`, and then report back.  Or, at the very least, provide a fully usable Compose file.

**Comment by joshtrichards** [comment] 2023-10-29 02:10
Closing due to insufficient information. If you continue to encounter this matter I suggest you follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com).

**Closed by joshtrichards** 2023-10-29 02:10 UTC
Labels: question, examples, needs info, integration: database
