### ISSUE TITLE
Auto-configuration based on environment variables does not work

### ISSUE THREAD

**Issue by pasikarkkainen** [nextcloud/docker#593] opened 2018-12-30 11:11 UTC
It seems auto-configuration using environment variables does not work when using docker image "nextcloud:15.0.0-apache".

docker-compose.yml:

```
version: "2"

services:

  nextcloud:
    image: nextcloud:15.0.0-apache
    container_name: nextcloud
    expose:
      - "80"
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - "./data:/var/www/html:z"
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASS=secretpassword
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecretpassword
    restart: always
```

Results in the first-time wizard having empty admin user/password, sqlite as the chosen database, and when one chooses mysql the mysql infos aren't filled in. So for some reason all those environment variables are ignored by the first-time wizard.

If I start a bash shell in the container, I can see the environment variables there just fine.

**Comment by chrisallenlane** [comment] 2019-01-05 18:07
I am encountering the same issue.

**Comment by J0WI** [comment] 2019-01-11 16:15
I'm not able to reproduce this

**Comment by darkdan21** [comment] 2019-01-19 22:02
I'm having the same issue using the example docker container configuration (tried both docker-compose/with-nginx-proxy/mariadb/fpm and docker-compose/with-nginx-proxy/postgres/fpm)

**Comment by ReneCD** [comment] 2019-02-18 22:17
I'm having the same problem.  The variables are simply being ignored.  Any idea why so many of us have this problem even though you can't reproduce it ?

**Comment by J0WI** [comment] 2019-02-21 08:08
I used the example in https://github.com/nextcloud/docker/issues/593#issue-394863856

**Comment by ReneCD** [comment] 2019-02-21 09:26
Example in #593?  That is this thread ?!?!

**Comment by dve** [comment] 2019-02-22 09:44
I got the same problem, but only on an existing installation. Copy & Pasting the nextcloud parts into a new docker-compose file and starting it works like a charme...

**Comment by SnowMB** [comment] 2019-02-23 00:51
Auto configuration will not overwrite settings if you already have an existing installation. If you are migrating or already have installed nextcloud, you have to edit the config file manually by attaching to the container or copying additional files into the container/volume.

**Comment by ReneCD** [comment] 2019-02-23 19:42
Actually this is a new installation. I have a lot of data that I have so far accessed through CISF/SMB, and the plan now is to install nextcloud/mysql/redis containers to serve files in my local lan as well as on the internet. My lan is behind a pfsense firewall with haproxy and acme/letsencrypt, so I am not concerned with that.   

So how do I import my standard windows folder into nextcrypt? I can only find pages talking about migration from owncrypt.

**Comment by ReneCD** [comment] 2019-02-25 05:38
Ok, I realize that is perhaps not really the relevant forum for that question, but how about this:

How can I ensure this is a new installation?  I did a "docker compose down", then "docker system prune -a".  That ought to have cleaned everything up, yet it still doesn't take the environment variables when I start over. I even went as far as to uninstall docker, remove /var/lib/docker, reinstall docker.

No matter what I do, it still comes up asking for the variables when i connect to the admin page... ?

**Comment by SnowMB** [comment] 2019-02-25 17:58
normally `docker-compose down -v ` should be enough (`-v` ensures that the created volumes get deleted)

Can you please post your docker-compose file?

**Comment by ReneCD** [comment] 2019-02-25 19:11
Sure:

```
version: '2'  

volumes:
  nextcloud:
  mariadb:

services:  
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /media/usb/share/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - mariadb
    volumes:
      - /media/usb/share/nextcloud/data/:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER = admin
      - NEXTCLOUD_ADMIN_PASSWORD = adminpass
      - NEXTCLOUD_DATA_DIR = /media/usb/share/nextcloud/data/
      - NEXTCLOUD_TRUSTED_DOMAINS = 192.168.1.90 
```

**Comment by SnowMB** [comment] 2019-02-25 20:13
You forgot the MySQL info for nextcloud to automatically configure the database connection. That's why the setup page is coming up. You need to add the following variables:

```
... 
  - MYSQL_HOST=mariadb
  - MYSQL_PASSWORD=pass  
  - MYSQL_DATABASE=nextcloud
  - MYSQL_USER=nextcloud
```

**Comment by ReneCD** [comment] 2019-02-25 21:41
So it should be under nextcloud and not under mariadb? Or both places?

**Comment by ReneCD** [comment] 2019-02-25 21:49
Ok so it should be under both containers then.  
It still comes up with the line "Create an admin account" but it's not clickable so I guess that's just a bug.

**Comment by ReneCD** [comment] 2019-03-02 21:25
Ok, I added this info, but it still asks to create an admin account.

**Comment by SnowMB** [comment] 2019-03-03 14:22
Are you sure you started a fresh install? Remove the created volumes with `docker-compose down - v`

**Comment by ReneCD** [comment] 2019-03-03 16:41
100% sure !

**Comment by ReneCD** [comment] 2019-03-03 21:21
Do I  need to manually clear out anything under /var/lib/docker?

**Comment by dve** [comment] 2019-03-04 08:35
> Auto configuration will not overwrite settings if you already have an existing installation. 

Ok, thanks for clarification - if restored my files and it works again

**Comment by Unrud** [comment] 2019-08-19 00:44
I think the problem is caused by a race condition.
The first start of MariaDB takes a long time (~2 minutes in my case).
The setup script in the nextcloud docker image only tries a limited number of times to run the install command (for ~30 seconds): https://github.com/nextcloud/docker/blob/2acb1df9ae522ab4c586f4e2e7084e47f9cbf4c6/16.0/apache/entrypoint.sh#L104

**Comment by aCLr** [comment] 2019-11-01 22:13
the same problem with postgres:
```
➜  nextcloud cat docker-compose.yml 
version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

  app:
    image: nextcloud:15.0.12-apache
    ports:
      - 7180:80
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    depends_on:
      - db
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_HOST: db:5432

➜  nextcloud docker-compose up -d db      
Creating nextcloud_db_1 ... 
Creating nextcloud_db_1 ... done
➜  nextcloud docker-compose logs db 
Attaching to nextcloud_db_1
db_1   | 2019-11-01 22:05:02.091 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
db_1   | 2019-11-01 22:05:02.092 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-11-01 22:05:02.092 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-11-01 22:05:02.112 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-11-01 22:05:02.172 UTC [18] LOG:  database system was shut down at 2019-11-01 22:04:35 UTC
db_1   | 2019-11-01 22:05:02.194 UTC [1] LOG:  database system is ready to accept connections
➜  nextcloud docker-compose up -d app
nextcloud_db_1 is up-to-date
Creating nextcloud_app_1 ... 
Creating nextcloud_app_1 ... done
➜  nextcloud docker inspect nextcloud_app_1|grep -A 20 Env        
            "Env": [
                "POSTGRES_HOST=db:5432",
                "POSTGRES_USER=nextcloud",
                "NEXTCLOUD_ADMIN_PASSWORD=admin",
                "POSTGRES_PASSWORD=nextcloud",
                "NEXTCLOUD_ADMIN_USER=admin",
                "POSTGRES_DB=nextcloud",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "APACHE_CONFDIR=/etc/apache2",
                "APACHE_ENVVARS=/etc/apache2/envvars",
                "PHP_EXTRA_BUILD_DEPS=apache2-dev",
                "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2 --disable-cgi",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie",
                "GPG_KEYS=CBAF69F173A0FEA4B537F470D66C9593118BCCB6 F38252826ACD957EF380D39F2F7956BC5DA04B5D",
                "PHP_VERSION=7.3.11",
                "PHP_URL=https://www.php.net/get/php-7.3.11.tar.xz/from/this/mirror",
                "PHP_ASC_URL=https://www.php.net/get/php-7.3.11.tar.xz.asc/from/this/mirror",
```
On the first URL checking I see "Create an admin account" message.

**Comment by sgreiner** [comment] 2019-11-07 00:40
Autoconfig based on ENV Vars is still broken in v17.
Tested with absolute blank system.

**Comment by huhugiter** [comment] 2019-11-23 15:22
same issue in v17, `NEXTCLOUD_ADMIN_PASSWORD` and `NEXTCLOUD_ADMIN_USER` not work.

**Comment by straumer** [comment] 2019-12-04 20:18
Tried with version 16 and 17 and this issue pops up.

**Comment by Xananax** [comment] 2019-12-17 03:30
Broken for me too. Possible mitigations:

- Wait longer, as suggested by @Unrud 
- Provide a way to trigger installation even if the container runs a second time (that is, allow passing an argument that triggers the install, additionally to the [version check](https://github.com/nextcloud/docker/blob/master/17.0/fpm-alpine/entrypoint.sh#L72))
- Remove any mention of the option of passing installation parameters in [Readme](https://github.com/nextcloud/docker/blob/master/README.md), or at least mention it's not working right now.

### If you've already created your volumes

Mitigation without intervening on the source, for us users consists in removing the faulty Nextcloud volume, and recreating it:

- `sudo docker volume ls` to get the nextcloud volume. It will be called `<project_name>_<volume_name>` (where `project_name` is the name of the directory).
- `sudo docker volume rm project_nextcloud` will give you an error with the name of the containers using this volume. Take this list, remove the commas, and paste it below:
- `sudo docker container rm <id1, id2, id3...>`
- run `sudo docker-compose up` again

### If you're fresh

If you haven't ever ran `docker-compose up`, instead of the above, you can let docker-compose create the db volume first.  
Assuming your database service is called `db`, you can run

```sh
sudo docker-compose -f docker-compose.yml up db
```
Let it do its thang, then kill it, and run:;

```sh
sudo docker-compose up
```
-----

Both those solutions work, which confirms it's a racing condition, though I have no idea why.

**Comment by eblondel** [comment] 2019-12-20 16:37
would be great to have an argument to auto-configure the nextcloud (triggering the install) when running the container.

**Comment by J0WI** [comment] 2020-01-11 00:52
This is due a performance regression in recent MariaDB releases, see https://github.com/docker-library/mariadb/issues/262

**Comment by bhammack** [comment] 2020-01-11 16:22
For anyone that's still struggling with this issue, I was able to come up with a solution in my docker-compose project. The cause of the issue has already been discussed above (mariadb takes ~60 seconds to setup on first launch, whereas nextcloud only performs 10 install attempts. If mariadb doesn't start up before nextcloud, the installation will fail and the parameters won't be applied)...

To resolve it, I mount the wait-for-it script found here https://github.com/vishnubob/wait-for-it into the container, override the entrypoint in my docker-compose file to call the script which then calls the entrypoint when the database container is accepting connections.


```
volumes:
      - ./configs/nextcloud/wait-for-it.sh:/bin/wait-for-it.sh # make sure this file is marked as executable on the host!
...
    entrypoint: sh -c '/bin/wait-for-it.sh nextcloud-db:3306 --timeout=120 && /entrypoint.sh apache2-foreground'
...
depends_on:
      - nextcloud-db
```

**Comment by eblondel** [comment] 2020-01-15 11:11
Hello, i'm still struggling with this, Is there a way to auto-config a docker nextcloud instance sticking with sqlite (default database)? I tried to configure this instance through Travis CI yaml file here https://github.com/eblondel/ocs4R/blob/master/.travis.yml#L52 Thanks

**Comment by choma** [comment] 2020-02-19 17:00
#963 didn't solve this, MariaDB is still taking **too much** time to start in some cases. And, since the related [MariaDB issue](https://github.com/docker-library/mariadb/issues/262) is still open, maybe this issue should be reopen too so people can see workarounds.

By now, I guess the best option is to use wait-for-it, as suggested by @bhammack .

**Comment by eblondel** [comment] 2020-02-19 17:07
Thanks, I've finally resolved my issue, and to me it works well, including with a SQLITE database.

**Comment by Aetherus** [comment] 2020-10-10 11:01
When installing with PostgreSQL/MySQL/MariaDB, nextcloud tries to use `"oc_${NEXTCLOUD_ADMIN_USER}"` as the database user, whether it's configured using environment variable or created on the webpage after installation.

**Comment by jakkso** [comment] 2020-11-23 20:57
Values set in `docker-compose.yml` are still being ignored and auto configuration does not work. I ran the db container separately prior to running all containers, as suggested by #593, which did not fix the problem. 
Additionally, after setting `NEXTCLOUD_TRUSTED_DOMAINS=mydomain` in nextcloud's environment section of docker-compose, I'm still greeted by the untrusted domain error message. I remoted into a running container and was able to see that while docker is passing `NEXTCLOUD_TRUSTED_DOMAINS` correctly, `config.php` doesn't contain the domain.

**Comment by krouw** [comment] 2020-11-23 23:37
I have the same issue here! Apparently it is a problem with the new release of the latest image, since a few days ago the environment variables were working normally

**Comment by jakkso** [comment] 2020-11-24 19:44
@krouw and anyone else having this problem: as a stopgap solution I copied `config.php` onto the host drive, mounted it as a volume, and hardcoded the needed values into it. If anyone else goes this route, be sure to adjust the permissions on `config.php`. I'm not a fan of hardcoding values, but I really just needed to get it running.

**Comment by TheFlow0360** [comment] 2021-02-08 09:08
any news here? I went and chose to use docker because it's "nice and clean", and now I have to integrate hacks like the wait-for-it script? I don't really get why this isn't treated with a higher priority, anyone running a real docker compose setup will run nto this problem

**Comment by mr-karan** [comment] 2021-02-13 07:33
Unsure why the issue is `closed` when so many of us are reporting that this issue still persists.

**Comment by ryjelsum** [comment] 2021-02-15 03:16
> Unsure why the issue is `closed` when so many of us are reporting that this issue still persists.

I've gotta second this. I've been having this issue for a number of weeks - cannot get the trusted domain environment variable to pass, from what I can tell looking at what I've done.

**Comment by Giom-fm** [comment] 2021-05-25 19:27
I have similar problems.
I am trying to connect a postgres database.
All ENV variables are set correctly except dbuser and dbpassword. The dbuser is always oc_admin. The password looks generated. I don't understand why the other variables are taken over correctly.

**Comment by wcdgit** [comment] 2022-03-12 22:27
I had the exact same behaviour as the the OP. I solved the problem by setting the environment variables
NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD. Without them there was no way to get the DB info to auto configure.

**Comment by clayrisser** [comment] 2022-12-22 20:39
@Giom-fm I'm facing the same issue. Did you ever figure this out?

**Comment by abraxaswd** [comment] 2023-02-24 08:57
This still does not work with postgresql and nextcloud 25. After configuring all ENV-vars and starting the container. There are errors as the installer tries to use the admin user of the install script. Furthermore it is not possible to use hyphens in admin user names. 
With mysql it works perfectly smooth....

**Comment by Giom-fm** [comment] 2023-02-24 09:52
@clayrisser Sorry for the delay.
Unfortunately, I still do not have a solution. To be honest, I don't even try anymore. This is such a basic feature and is not taken into account by the devs.

**Comment by Jannik44** [comment] 2023-12-24 10:57
Hello, same issue here, but with an already existing mariadb database, i verified that the database works and configured 'nextcloud' ad the database user in the cdocker compose file but in the logs i still see it using oc_admin, this is weird, and also cant get past the first run configuration page because it always says my db username or password is wrong, why is that still an issue after a so long time?

**Comment by joshtrichards** [comment] 2024-01-16 00:11
This Issue is a hodgepodge of loads of different situations. Many of these are unrelated. Some have since been fixed. There have also been numerous documentation revisions.

The original report was also already addressed so I'm closing this issue. But not without some awareness there are possibly some legitimate bug reports in here.

Unfortunately it's impossible to isolate each of the remaining situations without a full bug report from each person because similar symptoms do not always equal the same underlying cause. I'm going to re-close this, but feel free to open individual issues *if* you think there is  bug in the *image* that you are experiencing today. 

To head off a few things, here's a quick summary of a few things off the top of my head I see above that weren't already addressed or seem worthy of re-mentioning:

- most of the auto-config variables are ineffective after you've installed/ran the image once against a given container's volume because the Nextcloud installer will not be re-triggered. The Compose file/environment variables are designed for deployment not ongoing configuration changes
- the `oc_admin` behavior is an upstream matter in Server. There may be some inconsistencies in how it's handled with PG vs MySQL/MariaDB - I dunno; But that's not a matter the image can solve. All the image does is pass along things to the Nextcloud installer which handles the actual db user creation. I do know I'm able to make both MariaDB and PG deployments from scratch, fully via Docker Compose, using any reasonably recent image here (take that for what it's worth: a sample size of one)
- the other matters where some combinations of variables work and others don't - either post on the Help Forums or create a dedicated issue for your situation if you think it's an actual image bug. I think one more relevant issue was already mentioned so there also already may be existing issues covering some of those
- let's try to keep each Issue focused on one matter

**Closed by joshtrichards** 2024-01-16 00:11 UTC
Labels: question, feature: auto config (environment variables)
