### ISSUE TITLE
Can't login to the nextloud

### ISSUE THREAD

**Issue by 4joke** [nextcloud/docker#1770] opened 2022-06-13 13:12 UTC
i using latest container I can't login after set up password. That's it. version nextcloud:23.0.5-apache working doesn't have this issue.

**Comment by theamazingnorad** [comment] 2022-06-15 20:55
Same here, although I was struggling with a more advanced installation.  For troubleshooting purposes, I created a new docker-compose instance and copied, verbatim, the "Base version - apache" per the instructions.  While I can access the web interface, I get the following error when trying to create the admin user. 

![image](https://user-images.githubusercontent.com/72026346/173924557-bda7c332-6574-4749-b33c-5f3d7a142b5a.png)


I get the following in the terminal

` ` ` 
db_1   | 2022-06-15 20:48:40+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
db_1   | 2022-06-15 20:48:40+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
db_1   |        command was: mariadbd --transaction-isolation=READ-COMMITTED --binlog-format=ROW --verbose --help --log-bin-index=/tmp/tmp.x58OGkI4Yi
db_1   |        Can't initialize timers
` ` ` 
System: EndeavourOS
Docker version 20.10.8, build 3967b7d
docker-compose version 1.21.2, build a133471

**Comment by Slevin7** [comment] 2022-06-17 17:10
Had 

> i using latest container I can't login after set up password. That's it. version nextcloud:23.0.5-apache working doesn't have this issue.

I had the same problem, a simple rebuild helped.

**Comment by 4joke** [comment] 2022-06-19 16:04
> I am thinking this might be an issue with MariaDB.
It's not a MariaDB related problem. I encountered it with sqlite.

**Comment by joshtrichards** [comment] 2023-07-22 15:32
Hi @4joke - Thanks for the report. Unfortunately it lacks basic information needed to reproduce. What command line did you use to run it? Or, if using Docker Compose, what is the contents of your Compose file?

@mohamedztema Ditto. Same questions as directed at @4joke 

@theamazingnorad If you copied the Base version compose file verbatim, did you also remember to modify the `MYSQL_ROOT_PASSWORD` and `MYSQL_PASSWORD` lines for both services? You shouldn't be getting prompted to configure anything other than the the admin account/password if you're compose file is complete. Please provide your actual compose file. Thanks.

**Comment by joshtrichards** [comment] 2023-10-21 19:08
Closing due to:

- lack of info 
- seems to be a configuration matter

This channel is for bug reports and enhancement ideas in the Nextcloud Docker image. I suggest the Nextcloud Help Forum as a resource for configuration/deployment/troubleshooting assistance.

**Closed by joshtrichards** 2023-10-21 19:08 UTC
