### ISSUE TITLE
No videos preview

### ISSUE THREAD

**Issue by rosalinamia3** [nextcloud/docker#1472] opened 2021-04-12 08:13 UTC
Hi to all,
i am new in here.
I am sorry but I have this problem on my nextcloud installation.
No video previews.
I have asked my server provider to install ffmpeg as I have no root privileges (where the ffmpeg directory should be installed?)
Nothing has changed. All the videos uploaded before and after the ffmpeg installation have no previews.
I have also updated my config file as follow:
'preview_libreoffice_path' => '/usr/bin/libreoffice',
'enable_previews' => true,
'enabledPreviewProviders' =>
 array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDown',
    2 => 'OC\\Preview\\OpenDocument',
    3 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\MSOffice2003',
    5 => 'OC\\Preview\\MSOfficeDoc',
    6 => 'OC\\Preview\\Image',
    7 => 'OC\\Preview\\Photoshop',
    8 => 'OC\\Preview\\TIFF',
    9 => 'OC\\Preview\\SVG',
   10 => 'OC\\Preview\\Font',
   11 => 'OC\\Preview\\MP3',
   12 => 'OC\\Preview\\Movie',
   13 => 'OC\\Preview\\MKV',
   14 => 'OC\\Preview\\MP4',
   15 => 'OC\\Preview\\AVI',
 ),
I have also added a cron job /public_html/occ preview:pre-generate -vvv but nothing happened.
I have installed the app Preview Generator and follow their instructions:
"The first time you install this app, before using a cron job, you properly want to generate all previews via: ./occ preview:generate-all -vvv

Important: To enable pre-generation of previews you must add php /var/www/nextcloud/occ preview:pre-generate to a system cron job that runs at times of your choosing."
But nothing happened.
Do you have any suggestions?
Is there a chance to have a support for this issue? Is this a problem that it will show up on every nextcloud installation?
Thanks in advance for your support.
Regards
![Schermata 2021-04-12 alle 10 00 06](https://user-images.githubusercontent.com/82366040/114361967-16bf9580-9b77-11eb-8098-3b507b344586.png)

**Comment by rosalinamia3** [comment] 2021-04-12 11:50
I am on a shared hosting server.

**Comment by J0WI** [comment] 2021-04-12 17:30
Duplicate of https://github.com/nextcloud/docker/issues/1432#issuecomment-817587140

**Closed by J0WI** 2021-04-12 17:30 UTC
