### ISSUE TITLE
fpm-alpine image needs imagemagick package

### ISSUE THREAD

**Issue by bkraul** [nextcloud/docker#759] opened 2019-05-23 14:27 UTC
Eventhough there now seems to be support for imagemagick on the fpm-alpine version, the resulting PHP environment does not support any image formats, including SVG. This is due to the image missing the `imagemagick` package, which needs to be added with:

```
apk add --no-cache imagemagick
```
https://github.com/nextcloud/docker/blob/001afbefb6674d86ed2fb5d8f1cb561e82dc8b86/16.0/fpm-alpine/Dockerfile#L54

**Comment by J0WI** [comment] 2019-06-04 16:09
This is not installed by default: https://github.com/nextcloud/docker/issues/594#issuecomment-459859737
It's available in our "full" example:
https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm-alpine/Dockerfile

**Comment by talesam** [comment] 2021-02-22 21:35
I installed version 21 of the nextcloud fpm and still has the same problem as SVG.

I'll put it in the web folder, here:

```
FROM nginx: alpine
COPY nginx.conf /etc/nginx/nginx.conf
```

But I believe that if you just put the line
`apk add --no-cache imagemagick`
It shouldn't work.

**Comment by J0WI** [comment] 2021-03-13 19:17
Duplicate of #1414

**Closed by J0WI** 2021-03-13 19:17 UTC
Labels: wontfix
