### ISSUE TITLE
Internal server error for /settings/admin/serverinfo

### ISSUE THREAD

**Issue by JianYiheng** [nextcloud/docker#1427] opened 2021-02-26 01:04 UTC
Server device: Raspberry 4B
System: Raspberry Pi OS Lite (with openmediavault installed)
Install instruction: ``docker run -d -p 4443:4443 -p 443:443 -p 8080:80 -v /mnt/Nextcloud/ncdata:/var/www/html --restart unless-stopped --name nextcloudpi arm32v7/nextcloud``
P.S. */mnt/Nextcloud/ncdata* is the point that external hard drive mounted on raspberry pi.

When I clicked *system*, I got the error **Internal server error**
![image](https://user-images.githubusercontent.com/20198891/109239181-ba044900-7789-11eb-8165-2d0e8e5acc98.png)
![image](https://user-images.githubusercontent.com/20198891/109239565-91308380-778a-11eb-8f7f-d337fd8245c8.png)

I got below messages from /settings/admin/logging tab.
```
[index] Error: Exception: Call to undefined method OC\DB\ConnectionAdapter::getParams() at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "index")
1. /var/www/html/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", OC\AppFramework\ ... {}, {section: "serve ... "})
2. /var/www/html/lib/base.php line 993
   OC\Route\Router->match("/settings/admin/serverinfo")
3. /var/www/html/index.php line 37
   OC::handleRequest()

GET /settings/admin/serverinfo
from 192.168.3.31 by admin at 2021-02-26T00:43:50+00:00
```

**Comment by FishOnTheGround** [comment] 2021-03-01 21:41
I have the exact same issue on almost same configuration. Using official nextcloud docker image on RPi4.

**Comment by magicalbeard** [comment] 2021-03-04 18:45
Same issue here - brand new install of docker/nextcloud on my server. The IP it presents is also not the IP of the server I am connected to.

**Comment by phantomski77** [comment] 2021-03-13 19:10
Same issue here. Everything else works OK. IP address provided is a localhost of Nextcloud container.

- Using Docker 20.10.5 on rPi4/Ubuntu 20.10.
- Nextcloud 21.0.0 latest official Docker image,
- Separate Docker bridge network just for Nextcloud. 
- Behind reverse proxy

```
[index] Error: Exception: Call to undefined method OC\DB\ConnectionAdapter::getParams() at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "index")
1. /var/www/html/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", OC\AppFramework\ ... {}, {section: "serve ... "})
2. /var/www/html/lib/base.php line 993
   OC\Route\Router->match("/settings/admin/serverinfo")
3. /var/www/html/index.php line 37
   OC::handleRequest()

GET /settings/admin/serverinfo
from 172.19.0.1 by xxx at 2021-03-13T18:25:03+00:00
```

**Comment by J0WI** [comment] 2021-03-14 18:28
Duplicate of https://github.com/nextcloud/serverinfo/issues/278

**Closed by J0WI** 2021-03-14 18:28 UTC
