### ISSUE TITLE
Missing php-bz2 module

### ISSUE THREAD

**Issue by d3xt3r01** [nextcloud/docker#2172] opened 2024-03-04 17:00 UTC
Default simple install yells this:

This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them: bz2. For more details see the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-php-modules).

Can we add this so we get rid of this warning?

**Comment by joshtrichards** [comment] 2024-03-04 17:44
Duplicate of #2118

**Closed by joshtrichards** 2024-03-04 17:44 UTC
