### ISSUE TITLE
issue when renaming the nextcloud volume in docker compose file

### ISSUE THREAD

**Issue by leolivier** [nextcloud/docker#1937] opened 2023-03-12 12:13 UTC
Hi
For some unknown reason, the .htaccess file in /var/www/html became unreadable with "bad message" errors 
I'm using docker compose and /var/www/html was mounted on a temporary volume named  nextcloud like that:
```
volumes:
  nextcloud:

services:
  nextcloud:
...
    volumes:
      - nextcloud:/var/www/html
...
```
It prevented nextcloud to restart, so I removed the container and tried to remove the volume nextcloud_nextcloud too but it failed as .htaccess was not removable.
So finally I just changed nextcloud to nextcloud2 in the docker file like that:
```
volumes:
  nextcloud2:

services:
  nextcloud:
...
    volumes:
      - nextcloud2:/var/www/html
...```

```
and restarted nextcloud.

It looks like in the situation, the /entrypoint.sh detects that nextcloud is not installed and tries to reinstall everything including starting the command `occ maintenance:install` but nextcloud is already installed actually!
So, maintenance:install command does not exist anymore, a lot of errors (10 tries) and then nextcloud finally restarted but some applications have disappeared in between (eg mail) and I had to reinstall them.

So, maybe, such a simple action as renaming a volume in the docker compose file should not lead to this situation?

**Comment by joshtrichards** [comment] 2023-03-22 16:55
I had some trouble following your report, but let's see if we can get this sorted out a bit.

Unfortunately it seems that a smaller issue (whatever happened to your .htaccess file) may have turned into a larger issue for you.

I'm not sure what you mean by "temporary" volume: your named volume `nextcloud` containing `/var/www/html` would have been vital as it would contain all your data (!) and the current iteration of NC installed within configured container "nextcloud".

It sounds like you created a new named volume called `nextcloud2` on Docker and referenced it from your existing container (in-place of the previous volume)? That would have effectively been starting from scratch!

You can't simply "rename" a volume like that - but that isn't a nextcloud issue so much as how Docker functions: https://docs.docker.com/storage/volumes/

You say you lost your apps, but what about your data (files/photos/etc)? They should have been lost too unless I'm misunderstanding the steps you went through.

**Comment by leolivier** [comment] 2023-03-22 20:39
First of all, thanks for looking at my issue @joshtrichards 
Maybe my post was a bit misleading as I did not mention that /var/www/html/data and config were mounted as "persistant" volumes on "named" directories:
- /docker/nextcloud/config:/var/www/html/config
- /hdd/nextcloud:/var/www/html/data
This is why I'm saying nextcloud volume was temporary which I admit is a wrong term but I meant I didn't care of its content which could be regenerated from scratch.
Second point, ok, I can't change nextcloud to nextcloud2 as it recreates nextcloud from scratch but then why "occ maintenance:install" is not working? There is something illogic here as this command is removed once nextcloud is installed only, so either it is already installed (although I changed the volume name) and we should not run the command or it is not installed yet and the command should still exist.
To answer your question on how I did the change and maybe reproduce it, I just stopped the container (docker compose down) then changed nextcloud to nextcloud2 in the docker-compose.yml file and restarted everything (docker compose up -d)
Maybe that at the end, the issue is just that I thought my apps were stored in the "named directories" volumes and it was wrong...

**Comment by martadinata666** [comment] 2023-03-23 03:19
original
```
  volumes:
    - /docker/nextcloud/config:/var/www/html/config
    - /docker/nextcloud/apps:/var/www/html/apps
    - /hdd/nextcloud:/var/www/html/data
```
nextcloud2
```
  volumes:
    - /docker/nextcloud/config:/var/www/html/config
    - /docker/nextcloud/apps:/var/www/html/apps
    - nextcloud2:/var/www/html/data
```
I assume something like that? it is better that you attach all volumes configuration. 
```What mean empty by the startup script is `/var/www/html` is empty by any means `no subfolder, no hidden files`.```

There are 2 place apps stored `/var/www/html/apps` and `/var/www/html/custom_apps` usually third-party apps are placed in `/var/www/html/custom_apps` path.

**Comment by leolivier** [comment] 2023-03-23 12:59
Actually no, strictly only renaming nextcloud in nextcloud2, so
Before:
volumes:
    - /docker/nextcloud/config:/var/www/html/config
    - /docker/nextcloud/apps:/var/www/html/apps
    - /hdd/nextcloud:/var/www/html/data
    - nextcloud:/var/www/html

After

  volumes:
    - /docker/nextcloud/config:/var/www/html/config
    - /docker/nextcloud/apps:/var/www/html/apps
    - /hdd/nextcloud:/var/www/html/data
    - nextcloud2:/var/www/html

So for me, except the mount points of volumes inside /var/www/html, it should be empty. And if it's not due to the mount points, this should not work either for a brand new installation with that kind of config.
I didn't check for custom_apps, why maybe my apps disappeared, I get that. Nevertheless, the "occ maintenance:install" issue remains...

**Comment by joshtrichards** [comment] 2024-06-01 17:19
I'm still not really following what the supposed bug is. You deleted your primary persistent volume (the one containing `/var/www/data` and created a new volume in its replace. What occurred sounds like expected behavior:

https://github.com/nextcloud/docker?tab=readme-ov-file#persistent-data

https://github.com/nextcloud/docker?tab=readme-ov-file#additional-volumes

> The setup I am using, specifically storing user data in a well known place and not in the standard docker repo seems very reasonable to me, even in a brand new installation and will result in an error with the user data totally empty.

I still don't follow. The situation you encountered is because you effectively deleted one of your data volumes. 

Perhaps the misunderstanding here is you're viewing `/var/www/html/` as not being part of your "data", but in this Docker image that folder is supposed to be kept as persistent. It *is* data. It's important. 

The underlying volume type doesn't matter nor does it matter if you use more granular additional volumes for the folders located under it (as described at https://github.com/nextcloud/docker?tab=readme-ov-file#additional-volumes

Can you point out where the behavior does not match what is documented?

**Comment by joshtrichards** [comment] 2024-10-10 15:54
[Following up on this mostly to document the edge case at the end]

> It looks like in the situation, the /entrypoint.sh detects that nextcloud is not installed and tries to reinstall everything including starting the command occ maintenance:install but nextcloud is already installed actually!

Kind of. You deleted the installation, in effect, by dumping the prior `nextcloud` volume and creating a new (empty) volume called `nextcloud2`. Well, technically I guess you could say it's "half installed" or some such, since you did keep your configs (and, oddly, your shipped apps, but not your `custom_apps` / app store installed apps - but that's mostly beside the point).

> why "occ maintenance:install" is not working? There is something illogic here as this command is removed once nextcloud is installed only, so either it is already installed (although I changed the volume name) and we should not run the command or it is not installed yet and the command should still exist.

The `maintenance:install` is disabled once there is a config in place that has `installed` set to `true`.

You kept your config but deleted (most of) your Server installation. 

> even in a brand new installation and will result in an error with the user data totally empty.

No it won't.

> So empty definition should at least test that 1rst level directory are empty and then consider /var/www/html as empty in this case... Also, I don't know if this is easy to do, but in case of reinstall, we should either re enable the maintenance:install command or not run it
[...]

There is no *reinstall*. There is only:

- Install (a one-time event)
- Upgrade


> So, maintenance:install command does not exist anymore, a lot of errors (10 tries) and then nextcloud finally restarted but some applications have disappeared in between (eg mail) and I had to reinstall them.

This is a bit of an edge case (IMO), but we could make the *Install mode* check in the entrypoint a bit more robust I suppose:

https://github.com/nextcloud/docker/blob/6c1075b88d7184b067ce7c685ed55d136f7f0635/docker-entrypoint.sh#L144-L148

https://github.com/nextcloud/docker/blob/6c1075b88d7184b067ce7c685ed55d136f7f0635/docker-entrypoint.sh#L183

Since `installed_version` is only pulled from the installation, on line 183 we could also check for the presence of `'installed' => true` (or even just checking if a config is present), and abort the installer if so to avoid what will be end up being a failed "installation attempt". Still wouldn't permit you do to do what you did, but probably not a bad idea to improve the robustness of our entrypoint.

That said, I don't think it's currently worth adding the extra logic for such an edge case, where the end result will still be the same: a broken situation the image didn't create and also cannot do anything about.

**Comment by joshtrichards** [comment] 2024-10-10 15:57
I'm going to close this out as a "won't fix" for now. We can always revisit later if someone desires.

**Closed by joshtrichards** 2024-10-10 15:57 UTC
Labels: question, needs info, data persistence, needs review
