### ISSUE TITLE
Unable to update custom image with smb support

### ISSUE THREAD

**Issue by tincturaginseng** [nextcloud/docker#1587] opened 2021-09-16 10:29 UTC
Docker version:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:06 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:35 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

My Dockerfile:
```
FROM nextcloud:production

RUN apt-get update && apt-get install -y procps smbclient && rm -rf /var/lib/apt/lists/*
```

My docker-compose.yml

```
version: '3'
services:

  app-test:
    build: ./app-server
    container_name: app-server-test
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - /app/nextcloud-test/app/nextcloud:/var/www/html
      - /app/nextcloud-test/app/data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
      - MYSQL_PASSWORD=samepass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db-test
    depends_on:
      - db-test

  db-test:
    image: mariadb
    container_name: db-server-test
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /app/nextcloud-test/db/data:/var/lib/mysql
      - /app/nextcloud-test/db/opt:/opt
      - /app/nextcloud-test/db/conf.d:/etc/mysql/conf.d
      - /app/nextcloud-test/db/initdb:/docker-entrypoint-initdb.d
      - /app/nextcloud-test/db/mysql-files:/var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
      - MYSQL_PASSWORD=samepass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
```

I try to build and start stack:
```
docker-compose up -d --build
```

and it failed with this errors:
```
Creating config file /etc/samba/smb.conf with new version
stat: cannot statx '/run/samba/upgrades/smb.conf': Operation not permitted
dpkg: error processing package samba-common (--configure):
 installed samba-common package post-installation script subprocess returned error exit status 1

...

dpkg: dependency problems prevent configuration of smbclient:
 smbclient depends on samba-common (= 2:4.13.5+dfsg-2); however:
  Package samba-common is not configured yet.

dpkg: error processing package smbclient (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of samba-common-bin:
 samba-common-bin depends on samba-common (= 2:4.13.5+dfsg-2); however:
  Package samba-common is not configured yet.

dpkg: error processing package samba-common-bin (--configure):
 dependency problems - leaving unconfigured

...

Errors were encountered while processing:
 samba-common
 smbclient
 samba-common-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'app-test' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y procps smbclient && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

I noticed that compared to the previous Debian release, the path for generating a temporary Samba configuration file has changed: **/var/run/samba/updates/smb.conf** -> **/run/samba/updates/smb.conf**

With nextcloud image version 21.0.3 builds work fine

**Comment by BorussiaPlayer17** [comment] 2021-09-19 11:13
https://github.com/nextcloud/docker/issues/1536

**Comment by tincturaginseng** [comment] 2021-09-20 05:33
> #1536

Thanks! But I have no problems with the database server. I have a problem when creating custom nextcloud image with SMB support - an error occurred when installing the smbclient package (samba-common and samba-common-bin as dependencies).

**Comment by BorussiaPlayer17** [comment] 2021-09-20 06:31
Thats right, but when you figure out your image problem you would be facing the mariadb bug if you don't stick it to 10.5. Was just a little hint. Sorry, i could have written more.

**Comment by Neffez** [comment] 2021-09-20 16:48
@BorussiaPlayer17 No, he probably won't because he set `--innodb-read-only-compressed=OFF`

@tincturaginseng did you try with libsmbclient-dev (so ` ... apt-get install -y procps smbclient libsmbclient-dev ...`) ? Works for me without any problems.

**Comment by tincturaginseng** [comment] 2021-09-21 04:48
> @tincturaginseng did you try with libsmbclient-dev (so ` ... apt-get install -y procps smbclient libsmbclient-dev ...`) ? Works for me without any problems.

Same errorr:
```
Step 1/2 : FROM nextcloud:production
production: Pulling from library/nextcloud
f8416d8bac72: Pull complete
2259392b425a: Pull complete
cfb39fc3daf5: Pull complete
5c501de24ca4: Pull complete
ccf5f97ffc5c: Pull complete
a408db913f46: Pull complete
43600da0ccdc: Pull complete
5c02271fcd34: Pull complete
906ec01e131c: Pull complete
47000bdda098: Pull complete
4b5ef9292e8e: Pull complete
6ec123e585be: Pull complete
60a4b15c3138: Pull complete
b1d40a939f1f: Pull complete
dc93ffe15042: Pull complete
00310bf733b7: Pull complete
2ec06ec0679b: Pull complete
1e5684c7b36d: Pull complete
6689f131dc0c: Pull complete
d5670bb53d34: Pull complete
Digest: sha256:4f2491a01d05b1f137bbc1571f35b3ba7854bea3bbfcb3a7866645a688e9b681
Status: Downloaded newer image for nextcloud:production
 ---> 3861c7a8d5d4
Step 2/2 : RUN apt-get update && apt-get install -y procps smbclient libsmbclient-dev && rm -rf /var/lib/apt/lists/*
 ---> Running in 7ae55100acfc
Get:1 http://deb.debian.org/debian bullseye InRelease [113 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [34.6 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8178 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2088 B]
Fetched 8410 kB in 4s (2385 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
procps is already the newest version (2:3.3.17-5).
procps set to manually installed.
The following additional packages will be installed:
  dbus dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client
  gpg-wks-server gpgconf gpgsm libapparmor1 libarchive13 libassuan0
  libavahi-client3 libavahi-common-data libavahi-common3 libcap2 libcups2
  libdbus-1-3 libgpgme11 libksba8 libldb2 liblmdb0 libmpdec3 libnpth0
  libpython3-stdlib libpython3.9 libpython3.9-minimal libpython3.9-stdlib
  libsmbclient libtalloc2 libtdb1 libtevent0 libwbclient0 pinentry-curses
  python3 python3-gpg python3-ldb python3-minimal python3-samba python3-talloc
  python3-tdb python3.9 python3.9-minimal samba-common samba-common-bin
  samba-dsdb-modules samba-libs
Suggested packages:
  default-dbus-session-bus | dbus-session-bus dbus-user-session libpam-systemd
  pinentry-gnome3 tor parcimonie xloadimage scdaemon lrzip cups-common
  pinentry-doc python3-doc python3-tk python3-venv python3.9-venv
  python3.9-doc binfmt-support heimdal-clients python3-markdown
  python3-dnspython cifs-utils
The following NEW packages will be installed:
  dbus dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client
  gpg-wks-server gpgconf gpgsm libapparmor1 libarchive13 libassuan0
  libavahi-client3 libavahi-common-data libavahi-common3 libcap2 libcups2
  libdbus-1-3 libgpgme11 libksba8 libldb2 liblmdb0 libmpdec3 libnpth0
  libpython3-stdlib libpython3.9 libpython3.9-minimal libpython3.9-stdlib
  libsmbclient libsmbclient-dev libtalloc2 libtdb1 libtevent0 libwbclient0
  pinentry-curses python3 python3-gpg python3-ldb python3-minimal
  python3-samba python3-talloc python3-tdb python3.9 python3.9-minimal
  samba-common samba-common-bin samba-dsdb-modules samba-libs smbclient
0 upgraded, 51 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.7 MB of archives.
After this operation, 101 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libapparmor1 amd64 2.13.6-10 [99.3 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 libdbus-1-3 amd64 1.12.20-2 [219 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 dbus amd64 1.12.20-2 [239 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 libavahi-common-data amd64 0.8-5 [124 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 libavahi-common3 amd64 0.8-5 [58.4 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 libavahi-client3 amd64 0.8-5 [62.1 kB]
Get:7 http://deb.debian.org/debian bullseye/main amd64 libcap2 amd64 1:2.44-1 [23.6 kB]
Get:8 http://deb.debian.org/debian bullseye/main amd64 libcups2 amd64 2.3.3op2-3+deb11u1 [350 kB]
Get:9 http://deb.debian.org/debian bullseye/main amd64 liblmdb0 amd64 0.9.24-1 [45.0 kB]
Get:10 http://deb.debian.org/debian bullseye/main amd64 libtalloc2 amd64 2.3.1-2+b1 [29.3 kB]
Get:11 http://deb.debian.org/debian bullseye/main amd64 libtdb1 amd64 1.4.3-1+b1 [49.9 kB]
Get:12 http://deb.debian.org/debian bullseye/main amd64 libtevent0 amd64 0.10.2-1 [37.1 kB]
Get:13 http://deb.debian.org/debian bullseye/main amd64 libldb2 amd64 2:2.2.0-3.1 [147 kB]
Get:14 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-minimal amd64 3.9.2-1 [801 kB]
Get:15 http://deb.debian.org/debian bullseye/main amd64 libmpdec3 amd64 2.5.1-1 [87.7 kB]
Get:16 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-stdlib amd64 3.9.2-1 [1684 kB]
Get:17 http://deb.debian.org/debian bullseye/main amd64 libpython3.9 amd64 3.9.2-1 [1691 kB]
Get:18 http://deb.debian.org/debian bullseye/main amd64 libwbclient0 amd64 2:4.13.5+dfsg-2 [311 kB]
Get:19 http://deb.debian.org/debian bullseye/main amd64 python3.9-minimal amd64 3.9.2-1 [1955 kB]
Get:20 http://deb.debian.org/debian bullseye/main amd64 python3-minimal amd64 3.9.2-3 [38.2 kB]
Get:21 http://deb.debian.org/debian bullseye/main amd64 python3.9 amd64 3.9.2-1 [466 kB]
Get:22 http://deb.debian.org/debian bullseye/main amd64 libpython3-stdlib amd64 3.9.2-3 [21.4 kB]
Get:23 http://deb.debian.org/debian bullseye/main amd64 python3 amd64 3.9.2-3 [37.9 kB]
Get:24 http://deb.debian.org/debian bullseye/main amd64 python3-ldb amd64 2:2.2.0-3.1 [45.6 kB]
Get:25 http://deb.debian.org/debian bullseye/main amd64 python3-talloc amd64 2.3.1-2+b1 [17.4 kB]
Get:26 http://deb.debian.org/debian bullseye/main amd64 samba-libs amd64 2:4.13.5+dfsg-2 [5754 kB]
Get:27 http://deb.debian.org/debian bullseye/main amd64 libsmbclient amd64 2:4.13.5+dfsg-2 [167 kB]
Get:28 http://deb.debian.org/debian bullseye/main amd64 libsmbclient-dev amd64 2:4.13.5+dfsg-2 [147 kB]
Get:29 http://deb.debian.org/debian bullseye/main amd64 samba-common all 2:4.13.5+dfsg-2 [166 kB]
Get:30 http://deb.debian.org/debian bullseye/main amd64 libarchive13 amd64 3.4.3-2+b1 [343 kB]
Get:31 http://deb.debian.org/debian bullseye/main amd64 smbclient amd64 2:4.13.5+dfsg-2 [508 kB]
Get:32 http://deb.debian.org/debian bullseye/main amd64 libassuan0 amd64 2.5.3-7.1 [50.5 kB]
Get:33 http://deb.debian.org/debian bullseye/main amd64 gpgconf amd64 2.2.27-2 [547 kB]
Get:34 http://deb.debian.org/debian bullseye/main amd64 libksba8 amd64 1.5.0-3 [123 kB]
Get:35 http://deb.debian.org/debian bullseye/main amd64 libnpth0 amd64 1.6-3 [19.0 kB]
Get:36 http://deb.debian.org/debian bullseye/main amd64 dirmngr amd64 2.2.27-2 [762 kB]
Get:37 http://deb.debian.org/debian bullseye/main amd64 gnupg-l10n all 2.2.27-2 [1084 kB]
Get:38 http://deb.debian.org/debian bullseye/main amd64 gnupg-utils amd64 2.2.27-2 [905 kB]
Get:39 http://deb.debian.org/debian bullseye/main amd64 gpg amd64 2.2.27-2 [927 kB]
Get:40 http://deb.debian.org/debian bullseye/main amd64 pinentry-curses amd64 1.1.0-4 [64.9 kB]
Get:41 http://deb.debian.org/debian bullseye/main amd64 gpg-agent amd64 2.2.27-2 [669 kB]
Get:42 http://deb.debian.org/debian bullseye/main amd64 gpg-wks-client amd64 2.2.27-2 [523 kB]
Get:43 http://deb.debian.org/debian bullseye/main amd64 gpg-wks-server amd64 2.2.27-2 [516 kB]
Get:44 http://deb.debian.org/debian bullseye/main amd64 gpgsm amd64 2.2.27-2 [645 kB]
Get:45 http://deb.debian.org/debian bullseye/main amd64 gnupg all 2.2.27-2 [825 kB]
Get:46 http://deb.debian.org/debian bullseye/main amd64 libgpgme11 amd64 1.14.0-1+b2 [281 kB]
Get:47 http://deb.debian.org/debian bullseye/main amd64 python3-gpg amd64 1.14.0-1+b2 [334 kB]
Get:48 http://deb.debian.org/debian bullseye/main amd64 python3-tdb amd64 1.4.3-1+b1 [20.6 kB]
Get:49 http://deb.debian.org/debian bullseye/main amd64 python3-samba amd64 2:4.13.5+dfsg-2 [2603 kB]
Get:50 http://deb.debian.org/debian bullseye/main amd64 samba-common-bin amd64 2:4.13.5+dfsg-2 [663 kB]
Get:51 http://deb.debian.org/debian bullseye/main amd64 samba-dsdb-modules amd64 2:4.13.5+dfsg-2 [390 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 27.7 MB in 1s (19.2 MB/s)
Selecting previously unselected package libapparmor1:amd64.
(Reading database ... 15120 files and directories currently installed.)
Preparing to unpack .../00-libapparmor1_2.13.6-10_amd64.deb ...
Unpacking libapparmor1:amd64 (2.13.6-10) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../01-libdbus-1-3_1.12.20-2_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.12.20-2) ...
Selecting previously unselected package dbus.
Preparing to unpack .../02-dbus_1.12.20-2_amd64.deb ...
Unpacking dbus (1.12.20-2) ...
Selecting previously unselected package libavahi-common-data:amd64.
Preparing to unpack .../03-libavahi-common-data_0.8-5_amd64.deb ...
Unpacking libavahi-common-data:amd64 (0.8-5) ...
Selecting previously unselected package libavahi-common3:amd64.
Preparing to unpack .../04-libavahi-common3_0.8-5_amd64.deb ...
Unpacking libavahi-common3:amd64 (0.8-5) ...
Selecting previously unselected package libavahi-client3:amd64.
Preparing to unpack .../05-libavahi-client3_0.8-5_amd64.deb ...
Unpacking libavahi-client3:amd64 (0.8-5) ...
Selecting previously unselected package libcap2:amd64.
Preparing to unpack .../06-libcap2_1%3a2.44-1_amd64.deb ...
Unpacking libcap2:amd64 (1:2.44-1) ...
Selecting previously unselected package libcups2:amd64.
Preparing to unpack .../07-libcups2_2.3.3op2-3+deb11u1_amd64.deb ...
Unpacking libcups2:amd64 (2.3.3op2-3+deb11u1) ...
Selecting previously unselected package liblmdb0:amd64.
Preparing to unpack .../08-liblmdb0_0.9.24-1_amd64.deb ...
Unpacking liblmdb0:amd64 (0.9.24-1) ...
Selecting previously unselected package libtalloc2:amd64.
Preparing to unpack .../09-libtalloc2_2.3.1-2+b1_amd64.deb ...
Unpacking libtalloc2:amd64 (2.3.1-2+b1) ...
Selecting previously unselected package libtdb1:amd64.
Preparing to unpack .../10-libtdb1_1.4.3-1+b1_amd64.deb ...
Unpacking libtdb1:amd64 (1.4.3-1+b1) ...
Selecting previously unselected package libtevent0:amd64.
Preparing to unpack .../11-libtevent0_0.10.2-1_amd64.deb ...
Unpacking libtevent0:amd64 (0.10.2-1) ...
Selecting previously unselected package libldb2:amd64.
Preparing to unpack .../12-libldb2_2%3a2.2.0-3.1_amd64.deb ...
Unpacking libldb2:amd64 (2:2.2.0-3.1) ...
Selecting previously unselected package libpython3.9-minimal:amd64.
Preparing to unpack .../13-libpython3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking libpython3.9-minimal:amd64 (3.9.2-1) ...
Selecting previously unselected package libmpdec3:amd64.
Preparing to unpack .../14-libmpdec3_2.5.1-1_amd64.deb ...
Unpacking libmpdec3:amd64 (2.5.1-1) ...
Selecting previously unselected package libpython3.9-stdlib:amd64.
Preparing to unpack .../15-libpython3.9-stdlib_3.9.2-1_amd64.deb ...
Unpacking libpython3.9-stdlib:amd64 (3.9.2-1) ...
Selecting previously unselected package libpython3.9:amd64.
Preparing to unpack .../16-libpython3.9_3.9.2-1_amd64.deb ...
Unpacking libpython3.9:amd64 (3.9.2-1) ...
Selecting previously unselected package libwbclient0:amd64.
Preparing to unpack .../17-libwbclient0_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking libwbclient0:amd64 (2:4.13.5+dfsg-2) ...
Selecting previously unselected package python3.9-minimal.
Preparing to unpack .../18-python3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking python3.9-minimal (3.9.2-1) ...
Setting up libpython3.9-minimal:amd64 (3.9.2-1) ...
Setting up python3.9-minimal (3.9.2-1) ...
Selecting previously unselected package python3-minimal.
(Reading database ... 15973 files and directories currently installed.)
Preparing to unpack .../python3-minimal_3.9.2-3_amd64.deb ...
Unpacking python3-minimal (3.9.2-3) ...
Selecting previously unselected package python3.9.
Preparing to unpack .../python3.9_3.9.2-1_amd64.deb ...
Unpacking python3.9 (3.9.2-1) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../libpython3-stdlib_3.9.2-3_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.9.2-3) ...
Setting up python3-minimal (3.9.2-3) ...
Selecting previously unselected package python3.
(Reading database ... 16018 files and directories currently installed.)
Preparing to unpack .../00-python3_3.9.2-3_amd64.deb ...
Unpacking python3 (3.9.2-3) ...
Selecting previously unselected package python3-ldb.
Preparing to unpack .../01-python3-ldb_2%3a2.2.0-3.1_amd64.deb ...
Unpacking python3-ldb (2:2.2.0-3.1) ...
Selecting previously unselected package python3-talloc:amd64.
Preparing to unpack .../02-python3-talloc_2.3.1-2+b1_amd64.deb ...
Unpacking python3-talloc:amd64 (2.3.1-2+b1) ...
Selecting previously unselected package samba-libs:amd64.
Preparing to unpack .../03-samba-libs_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking samba-libs:amd64 (2:4.13.5+dfsg-2) ...
Selecting previously unselected package libsmbclient:amd64.
Preparing to unpack .../04-libsmbclient_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking libsmbclient:amd64 (2:4.13.5+dfsg-2) ...
Selecting previously unselected package libsmbclient-dev:amd64.
Preparing to unpack .../05-libsmbclient-dev_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking libsmbclient-dev:amd64 (2:4.13.5+dfsg-2) ...
Selecting previously unselected package samba-common.
Preparing to unpack .../06-samba-common_2%3a4.13.5+dfsg-2_all.deb ...
Unpacking samba-common (2:4.13.5+dfsg-2) ...
Selecting previously unselected package libarchive13:amd64.
Preparing to unpack .../07-libarchive13_3.4.3-2+b1_amd64.deb ...
Unpacking libarchive13:amd64 (3.4.3-2+b1) ...
Selecting previously unselected package smbclient.
Preparing to unpack .../08-smbclient_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking smbclient (2:4.13.5+dfsg-2) ...
Selecting previously unselected package libassuan0:amd64.
Preparing to unpack .../09-libassuan0_2.5.3-7.1_amd64.deb ...
Unpacking libassuan0:amd64 (2.5.3-7.1) ...
Selecting previously unselected package gpgconf.
Preparing to unpack .../10-gpgconf_2.2.27-2_amd64.deb ...
Unpacking gpgconf (2.2.27-2) ...
Selecting previously unselected package libksba8:amd64.
Preparing to unpack .../11-libksba8_1.5.0-3_amd64.deb ...
Unpacking libksba8:amd64 (1.5.0-3) ...
Selecting previously unselected package libnpth0:amd64.
Preparing to unpack .../12-libnpth0_1.6-3_amd64.deb ...
Unpacking libnpth0:amd64 (1.6-3) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../13-dirmngr_2.2.27-2_amd64.deb ...
Unpacking dirmngr (2.2.27-2) ...
Selecting previously unselected package gnupg-l10n.
Preparing to unpack .../14-gnupg-l10n_2.2.27-2_all.deb ...
Unpacking gnupg-l10n (2.2.27-2) ...
Selecting previously unselected package gnupg-utils.
Preparing to unpack .../15-gnupg-utils_2.2.27-2_amd64.deb ...
Unpacking gnupg-utils (2.2.27-2) ...
Selecting previously unselected package gpg.
Preparing to unpack .../16-gpg_2.2.27-2_amd64.deb ...
Unpacking gpg (2.2.27-2) ...
Selecting previously unselected package pinentry-curses.
Preparing to unpack .../17-pinentry-curses_1.1.0-4_amd64.deb ...
Unpacking pinentry-curses (1.1.0-4) ...
Selecting previously unselected package gpg-agent.
Preparing to unpack .../18-gpg-agent_2.2.27-2_amd64.deb ...
Unpacking gpg-agent (2.2.27-2) ...
Selecting previously unselected package gpg-wks-client.
Preparing to unpack .../19-gpg-wks-client_2.2.27-2_amd64.deb ...
Unpacking gpg-wks-client (2.2.27-2) ...
Selecting previously unselected package gpg-wks-server.
Preparing to unpack .../20-gpg-wks-server_2.2.27-2_amd64.deb ...
Unpacking gpg-wks-server (2.2.27-2) ...
Selecting previously unselected package gpgsm.
Preparing to unpack .../21-gpgsm_2.2.27-2_amd64.deb ...
Unpacking gpgsm (2.2.27-2) ...
Selecting previously unselected package gnupg.
Preparing to unpack .../22-gnupg_2.2.27-2_all.deb ...
Unpacking gnupg (2.2.27-2) ...
Selecting previously unselected package libgpgme11:amd64.
Preparing to unpack .../23-libgpgme11_1.14.0-1+b2_amd64.deb ...
Unpacking libgpgme11:amd64 (1.14.0-1+b2) ...
Selecting previously unselected package python3-gpg.
Preparing to unpack .../24-python3-gpg_1.14.0-1+b2_amd64.deb ...
Unpacking python3-gpg (1.14.0-1+b2) ...
Selecting previously unselected package python3-tdb.
Preparing to unpack .../25-python3-tdb_1.4.3-1+b1_amd64.deb ...
Unpacking python3-tdb (1.4.3-1+b1) ...
Selecting previously unselected package python3-samba.
Preparing to unpack .../26-python3-samba_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking python3-samba (2:4.13.5+dfsg-2) ...
Selecting previously unselected package samba-common-bin.
Preparing to unpack .../27-samba-common-bin_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking samba-common-bin (2:4.13.5+dfsg-2) ...
Selecting previously unselected package samba-dsdb-modules:amd64.
Preparing to unpack .../28-samba-dsdb-modules_2%3a4.13.5+dfsg-2_amd64.deb ...
Unpacking samba-dsdb-modules:amd64 (2:4.13.5+dfsg-2) ...
Setting up libksba8:amd64 (1.5.0-3) ...
Setting up liblmdb0:amd64 (0.9.24-1) ...
Setting up libapparmor1:amd64 (2.13.6-10) ...
Setting up libarchive13:amd64 (3.4.3-2+b1) ...
Setting up libtdb1:amd64 (1.4.3-1+b1) ...
Setting up libnpth0:amd64 (1.6-3) ...
Setting up samba-common (2:4.13.5+dfsg-2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Creating config file /etc/samba/smb.conf with new version
stat: cannot statx '/run/samba/upgrades/smb.conf': Operation not permitted
dpkg: error processing package samba-common (--configure):
 installed samba-common package post-installation script subprocess returned error exit status 1
Setting up libassuan0:amd64 (2.5.3-7.1) ...
Setting up libcap2:amd64 (1:2.44-1) ...
Setting up libtalloc2:amd64 (2.3.1-2+b1) ...
Setting up libtevent0:amd64 (0.10.2-1) ...
Setting up gnupg-l10n (2.2.27-2) ...
Setting up libavahi-common-data:amd64 (0.8-5) ...
Setting up libdbus-1-3:amd64 (1.12.20-2) ...
Setting up dbus (1.12.20-2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
dpkg: dependency problems prevent configuration of smbclient:
 smbclient depends on samba-common (= 2:4.13.5+dfsg-2); however:
  Package samba-common is not configured yet.

dpkg: error processing package smbclient (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of samba-common-bin:
 samba-common-bin depends on samba-common (= 2:4.13.5+dfsg-2); however:
  Package samba-common is not configured yet.

dpkg: error processing package samba-common-bin (--configure):
 dependency problems - leaving unconfigured
Setting up libmpdec3:amd64 (2.5.1-1) ...
Setting up gpgconf (2.2.27-2) ...
Setting up libldb2:amd64 (2:2.2.0-3.1) ...
Setting up gpg (2.2.27-2) ...
Setting up libpython3.9-stdlib:amd64 (3.9.2-1) ...
Setting up libpython3-stdlib:amd64 (3.9.2-3) ...
Setting up gnupg-utils (2.2.27-2) ...
Setting up pinentry-curses (1.1.0-4) ...
Setting up gpg-agent (2.2.27-2) ...
Setting up gpgsm (2.2.27-2) ...
Setting up libavahi-common3:amd64 (0.8-5) ...
Setting up libgpgme11:amd64 (1.14.0-1+b2) ...
Setting up libwbclient0:amd64 (2:4.13.5+dfsg-2) ...
Setting up dirmngr (2.2.27-2) ...
Setting up libpython3.9:amd64 (3.9.2-1) ...
Setting up gpg-wks-server (2.2.27-2) ...
Setting up libavahi-client3:amd64 (0.8-5) ...
Setting up python3.9 (3.9.2-1) ...
Setting up gpg-wks-client (2.2.27-2) ...
Setting up python3 (3.9.2-3) ...
running python rtupdate hooks for python3.9...
running python post-rtupdate hooks for python3.9...
Setting up python3-tdb (1.4.3-1+b1) ...
Setting up python3-gpg (1.14.0-1+b2) ...
Setting up python3-ldb (2:2.2.0-3.1) ...
Setting up libcups2:amd64 (2.3.3op2-3+deb11u1) ...
Setting up gnupg (2.2.27-2) ...
Setting up python3-talloc:amd64 (2.3.1-2+b1) ...
Setting up samba-libs:amd64 (2:4.13.5+dfsg-2) ...
Setting up libsmbclient:amd64 (2:4.13.5+dfsg-2) ...
Setting up libsmbclient-dev:amd64 (2:4.13.5+dfsg-2) ...
Setting up samba-dsdb-modules:amd64 (2:4.13.5+dfsg-2) ...
Setting up python3-samba (2:4.13.5+dfsg-2) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for libc-bin (2.31-13) ...
Errors were encountered while processing:
 samba-common
 smbclient
 samba-common-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'app-test' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y procps smbclient libsmbclient-dev && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
Maybe you install smbclient into running image?

**Comment by Neffez** [comment] 2021-09-27 10:12
The only difference to mine is I don't use the production image:
```
FROM nextcloud

RUN apt-get update && apt-get install -y smbclient libsmbclient-dev && rm -rf /var/lib/apt/lists/*
```

**Comment by J0WI** [comment] 2021-09-30 13:07
I assume your Docker/Kernel is too old: https://github.com/nextcloud/docker/issues/1589 https://github.com/nextcloud/docker/issues/1579

**Comment by J0WI** [comment] 2022-02-02 23:26
Closing as duplicate of https://github.com/nextcloud/docker/issues/1589

**Closed by J0WI** 2022-02-02 23:26 UTC
