### ISSUE TITLE
fpm-alpine FULL - Dockerfile build fails on Step 5 - "Copy supervisord.conf"

### ISSUE THREAD

**Issue by james-cook** [nextcloud/docker#966] opened 2020-01-15 12:45 UTC
From: https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm-alpine/Dockerfile today.

Tail end of Dockerfile is:

```
COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
```

Build reports:

>   COPY failed: stat /var/lib/docker/tmp/docker-builder167487155/supervisord.conf: no such file or directory, logs:

**Comment by J0WI** [comment] 2020-01-16 18:55
I cannot reproduce with the most recent image.

**Comment by tilosp** [comment] 2020-01-17 12:15
To me this looks like there is no `supervisord.conf` file in the directory where your Dockerfile is located

**Comment by meonkeys** [comment] 2022-08-26 23:53
I got the same Docker build error when I forgot to actually do what @tilosp recommends. Seems safe to close this issue unless we want to make it one about improving https://github.com/nextcloud/docker/blob/master/.examples/README.md

**Closed** 2022-10-14 23:36 UTC
