### ISSUE TITLE
example docker-compose with nginx proxy fails to connect with sync client

### ISSUE THREAD

**Issue by flower1024** [nextcloud/docker#884] opened 2019-10-01 21:39 UTC
docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml

if you want to connect with mobile or desktop sync client you must run this command after installation:
docker-compose exec --user www-data app php occ config:system:set overwriteprotocol --value="https"

sadly i dont know how to integrate this myself, otherwise i would have supplied a fix

**Comment by kesselb** [comment] 2019-10-01 21:47
Thanks for reporting :+1: 

Duplicate of https://github.com/nextcloud/docker/issues/851

**Closed by kesselb** 2019-10-01 21:47 UTC
