### ISSUE TITLE
Docker, update from 16.0.3 to 16.0.4, container start failed, exit 137

### ISSUE THREAD

**Issue by myhubacct** [nextcloud/docker#842] opened 2019-08-22 09:59 UTC
have updated my local nextcloud docker container via pull and build. The update process worked fine. Trying to start the final updated container ended with exit 137 after a short while.

$ docker-compose -f \<path> -p \<name> --verbose --project-directory \<path> build --pull

There was no error shown during the build process. After the next command the nextcloud container will die after a short while with exit code 137

$ docker-compose -f \<path> -p \<name> --verbose --project-directory \<path> up

Already deleted the container with the corresponding images and restart the build process. with the same result.

How can I get nextcloud up and running again? Where could I start debugging the issue best?

**Comment by J0WI** [comment] 2019-08-31 00:37
On what CPU architecture? This might be a duplicate of docker-library/php#822
Could you provide some logs?

**Comment by myhubacct** [comment] 2019-09-03 06:57
Unfortunately I can’t actually. In the meantime I had cleaned out the docker containers including images and so on. Afterwards I have done a fresh build and till now the error has not occurred again.

**Closed** 2019-09-04 22:58 UTC
