### ISSUE TITLE
Upgrade between major versions (n > 2) fails and breaks the installation

### ISSUE THREAD

**Issue by wsw70** [nextcloud/docker#1650] opened 2021-12-02 13:49 UTC
Upgrading between two major versions is not possible. Fair enough.

Attempting the upgrade fails (so far so good) but also **breaks the current installation** (at least for the official docker image). This is not acceptable.

--- 

**Expected behaviour**: a message telling that an upgrade above two major versions is not possible **and that's all** (no changes to the installation)

**What happens**: the database gets messed up, with a partial upgrade.

This is really a major bug (not an issue or inconvenience) - a **known limitation**, instead of being handed gracefully breaks an installation.

**Versions**: attempt to upgrade from 21 to 23. Now I have a broken Nextcloud service.

**Comment by AlexCloudDev** [comment] 2021-12-03 18:54
Hi,
I've got the same problem.
Plus, i was on 22.1.1.2, so didn't upgrade from two major versions.
This ist absolutely not acceptable.
No i even can't go back, because it says my data is on 23 and can't be downgraded.

How ist this possible????

**Comment by wsw70** [comment] 2021-12-03 19:18
> I tried to upgrade from 22 to 23 as suggested and now my whole installation is offline.

I work in IT and development and this is honestly disheartening. I understand that there are bugs and everything but when some software says "ah, we checked and you cannot upgrade n+2", and then proceeds to break the install - this is simply insane.

I ended up restoring everything from a backup, I could not find any other way to get off the "incompatible version" loop.

**Comment by AlexCloudDev** [comment] 2021-12-03 21:29
Hey,
i managed to repair my installation.
I was on 22.1.1.2 before the update to 23 failed because of Exception: Updates between multiple major versions and downgrades are unsupported.
So i restored the version.php file from a backup from my 22 installation.
After that i pulled and run the latest 22 image.
Then i could update to it manually to 22.2.3 via the web interface.
Finally i set maintenance mode off via occ.
At least my nextcloud instance runs again, but not at 23.....

**Comment by wsw70** [comment] 2021-12-03 22:03
> At least my nextcloud instance runs again, but not at 23.....

What I did was to restore my 21 version, then do two upgrades (21 → 22 and then 22 → 23). This worked flawlessly.

**Comment by J0WI** [comment] 2022-02-02 23:02
see https://github.com/nextcloud/server/issues/2270

**Comment by J0WI** [comment] 2022-02-02 23:04
duplicate of https://github.com/nextcloud/docker/issues/1129

**Closed by J0WI** 2022-02-02 23:04 UTC
Labels: upstream
