### ISSUE TITLE
upgrade from 22 to 23 with REDIST_HOST set via docker -e fails

### ISSUE THREAD

**Issue by darena67** [nextcloud/docker#1691] opened 2022-02-09 19:08 UTC
Hi if I have REDIST_HOST set in my docker run command as a -e REDIST_HOST="hostname.blah" then I get a:

Configuring Redis as session handler
/entrypoint.sh: 60: Bad substitution

removing REDIST_HOST from docker run line fixes the error and nextcloud starts up.

**Comment by mr700** [comment] 2022-02-19 22:57
Duplicate of #1699?

**Closed** 2022-04-27 08:38 UTC
Labels: duplicate
