### ISSUE TITLE
Docker image auto-logins first visitor as ADMIN even when admin user + password are set

### ISSUE THREAD

**Issue by JonasT** [nextcloud/docker#455] opened 2018-09-11 10:43 UTC
The docker image at hub.docker.com/_/nextcloud appears to auto-login the first visitor as administrator even when admin user and password are set via `NEXTCLOUD_ADMIN_USER`, `NEXTCLOUD_ADMIN_PASSWORD`. I would suggest this is **extremely unexpected** for an instance with a preconfigured password, and therefore a potential security pitfall for anyone setting up a nextcloud with docker.

### Steps to reproduce
1. Start docker container with fresh/empty data volumes and `NEXTCLOUD_ADMIN_USER`, `NEXTCLOUD_ADMIN_PASSWORD` set, as well as `MYSQL_USER`, `MYSQL_DATABASE`, `MYSQL_PASSWORD, MYSQL_HOST` (such that no setup wizard is required)
2. Wait until instance runs
3. Visit instance

### Expected behaviour
Login mask since an admin password was set, and database and everything else is also preconfigured via environment variables (=no setup wizard necessary)

### Actual behaviour
While there isn't actually a setup wizard, I'm dropped right into the files overview with what appears *administrator rights*. (or anyone else will who manages to visit it before me, I tested this with the help of someone else from their computer) The second visitor gets a login mask, but by then it might be too late

### Server configuration

**Operating system**: Ubuntu

**Web server:** as packaged in the docker image

**Database:** latest redis and mariadb images from dockerhub

**PHP version:** as packaged in the docker image

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** no, fresh install

**Where did you install Nextcloud from:** hub.docker.com

**Other things:**

I skipped checking the other things (server config, apps, LDAP, ...) since this happens 100% every time with a fresh docker instance for me. However, if you have trouble reproducing, I'll gladly provide any of the other information if that is needed

**Comment by SnowMB** [comment] 2018-09-11 13:40
This is an upstream issue. Duplicate of #242.

**Comment by SnowMB** [comment] 2018-09-11 13:42
Also see https://github.com/nextcloud/server/issues/8653

**Comment by JonasT** [comment] 2018-09-11 13:47
Ok but can't you see that in this specific instance it doesn't make ANY sense? I already made a ticket in the server repo, and others did, and it would really suck if this would remain unfixed just because of ticket politics.

Yes, it is an intentional "feature" of upstream. Yes, it makes sense for the normal install. But **in this particular configuration** it doesn't make sense at all, and is a major pitfall.

I feel like you're asking *me* how you and the server people can figure out who needs to do what on which side to make this work better. I'm the wrong person to ask for that!

**Comment by JonasT** [comment] 2018-09-11 13:49
Basically this is still quite docker-specific because as far as I understand this, only in the docker case, the password may already be presubmitted via env vars. (And in this case, it is extremely unexpected if the first person to visit still gets admin rights)

And I really think it should be fixed

**Comment by tilosp** [comment] 2018-09-11 13:51
@SnowMB in the case when all vars for required are set, we could run `occ maintenance:install` directly

**Comment by SnowMB** [comment] 2018-09-11 13:56
@tilosp I think this is related and blocks us from doing so (haven't tested anything):

https://github.com/nextcloud/server/issues/8524

**Comment by tilosp** [comment] 2018-09-11 13:58
@SnowMB it should't. We should be able to access the vars from the entrypoint.sh script and pass them to the `occ maintenance:install` command.

**Comment by SnowMB** [comment] 2018-09-11 15:41
Ah I see. Should be possible. We just have to check if everything available and skip the autoconfig.php in that case.

```
sudo -u www-data php occ  maintenance:install --database
"mysql" --database-name "nextcloud"  --database-user "root" --database-pass
"password" --admin-user "admin" --admin-pass "password"
```

https://docs.nextcloud.com/server/14/admin_manual/installation/command_line_installation.html

**Closed** 2018-09-29 16:40 UTC
Labels: enhancement, image
