### ISSUE TITLE
Apache image does not replace remote addr from X-Real-IP

### ISSUE THREAD

**Issue by HJunyuan** [nextcloud/docker#1313] opened 2020-12-01 15:38 UTC
The following [snippet from the readme](https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol) states:
```text
The apache image will replace the remote addr (ip address visible to Nextcloud)
with the ip address from X-Real-IP if the request is coming from a proxy in
10.0.0.0/8, 172.16.0.0/12 or 192.168.0.0/16 by default.
```

Using the provided [docker-compose apache example](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache), I've managed to set up a Nextcloud instance successfully that is accessible from the internet. However, the Nextcloud app does not seem to be obtaining the correct IP from the Nginx reverse proxy.

When I run `docker-compose logs -f`, the proxy logs show the correct public IPs but the app logs display the internal Docker IP (e.g. `172.26.0.x`) instead.

I've replaced `index.php` with this snippet to get a better understanding:
```php
<?php
print_r($_SERVER);
?>
```
which printed:
```php
//...
[HTTP_X_REAL_IP] => 100.x.x.x // Public IP
[HTTP_X_FORWARDED_FOR] => 100.x.x.x // Public IP
[HTTP_X_FORWARDED_PROTO] => https
[HTTP_X_FORWARDED_SSL] => on
[HTTP_X_FORWARDED_PORT] => 443
// ...
[SERVER_ADDR] => 172.26.0.5
[SERVER_PORT] => 80
[REMOTE_ADDR] => 172.26.0.2
// ...
```

**What is expected**
The Apache image should automatically replace `REMOTE_ADDR` with `X-Real-IP` since the request is coming from an internal IP block `172.16.0.0/12`.

**What actually happens**
`REMOTE_ADDR` remains as the internal IP of the proxy.

**Comment by joshtrichards** [comment] 2024-04-23 22:31
Duplicate of #1103

**Closed by joshtrichards** 2024-04-23 22:31 UTC
Labels: bug, examples, integration: proxy
