### ISSUE TITLE
Preview of video's

### ISSUE THREAD

**Issue by johansmitsnl** [nextcloud/docker#135] opened 2017-07-28 16:05 UTC
Why are there no preview generated with the docker image?

**Comment by SnowMB** [comment] 2017-07-31 09:17
#63 Might be related, also in todo for rework of examples section #125

**Comment by johansmitsnl** [comment] 2017-07-31 18:27
@SnowMB that sounds like it. But I agree with @nalt in #63 that it should be in of have different tags.
The suggestion of the ticket is that you could add/modify the docker image yourself if you want more. But this passes the main issue that we use a docker image to prevent maintaining it ourself and we just want to run one that works from the hub. Contributing makes it easier when there are issues and not everyone has to solve them theirselves.
Or are the example options that you can pass to the env to enable/disable certain functionalities?

**Comment by tilosp** [comment] 2017-08-26 14:06
Duplicate of #63

**Closed** 2017-08-26 14:15 UTC
Labels: help wanted, question
