### ISSUE TITLE
How to use docker secrets for DB/admin passwords?

### ISSUE THREAD

**Issue by martianrock** [nextcloud/docker#270] opened 2018-02-24 15:52 UTC
Can anyone provide any hints how to use nextcloud with DB and other passwords in docker secrets instead of plain passwords in docker-compose/command line or in .env files?

**Comment by mr-bolle** [comment] 2018-02-25 17:02
Hi, have you check the [docker documentation](https://docs.docker.com/compose/compose-file/#secrets-configuration-reference). 
Or have a look on this [stackoverflow thread](https://stackoverflow.com/questions/42139605/how-do-you-manage-secret-values-with-docker-compose-v3-1)

If I find time, I'll look at this service once.

**Comment by staticcat** [comment] 2018-06-11 12:12
If your using postgres you can write something like the following:

`version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_db_password
    env_file:
      - db.env
    secrets:
      - postgres_db_password
.
.
.
secrets:
  postgres_db_password:
    file: ./secrets/postgress_db_password`

If your using swarm you can even use external secrets define through the swarm command line.

**Comment by tilosp** [comment] 2018-08-24 13:37
Duplicate of #385

**Closed by tilosp** 2018-08-24 13:37 UTC
