### ISSUE TITLE
Error about docker-compose deploying Redis services

### ISSUE THREAD

**Issue by ai30328348** [nextcloud/docker#2219] opened 2024-05-17 08:02 UTC
I don't want to use root to run nextcloud, so I've found out if  
' - REDIS_HOST=redis configured
      - REDIS_HOST_PORT=6379', nextcloud will not start due to permission issues, when this configuration is removed, this problem will not occur after manually setting the Redis configuration for NextCloud. I think it's a bug

**### This is my  docker-compose.yml**
`
version: '2'

volumes:
  nextcloud:
  redis:
services:
  redis:
    image: redis
    networks:
       - my_net

  app:
    image: nextcloud
    user: "1000:1000"
    restart: always
    ports:
      - 8080:80
    volumes:
      - /config/nextcloud:/var/www/html
      - /mnt/:/mnt
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
        #- REDIS_HOST_PASSWORD=
      - APACHE_BODY_LIMIT=0
    networks:
         - my_net

networks:
  my_net:
    external: true`

******When I run, it shows****** 
redis  | 1:M 17 May 2024 06:39:56.106 * Ready to accept connections tcp
app-1  | Configuring Redis as session handler
app-1  | /entrypoint.sh: 111: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied
app-1 exited with code 0
app-1 exited with code 2
app-1  | Configuring Redis as session handler
app-1  | /entrypoint.sh: 111: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied
app-1  | Configuring Redis as session handler
app-1  | /entrypoint.sh: 111: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied
app-1  | Configuring Redis as session handler

**Comment by joshtrichards** [comment] 2024-05-17 17:58
Duplicate of #763

**Closed by joshtrichards** 2024-05-17 17:58 UTC
